### ISSUE TITLE
Plz do not install workflow automatically

### ISSUE THREAD

**Issue by joelcho** [wfrest/wfrest#105]
I think it is not good to install [workflow](https://github.com/sogou/workflow) automatically at build time.

Try to prompt people how to install that library when it's not found.

Or, install it in `CMAKE_BUILD_DIRECTORY` ( currently `/usr/local` ) maybe a good way.

**Comment by chanchann** [comment]
Ok, thanks for you suggestion. I will try to fix it.

**Comment by chanchann** [comment]
Now you can just make like this:

```
git clone --recursive https://github.com/wfrest/wfrest
cd wfrest
make
sudo make install
```

Thanks for your suggestion again.
