### ISSUE TITLE
BUG多了一个*

### ISSUE THREAD

**Issue by HzjFirst** [wfrest/wfrest#107]
![image](https://user-images.githubusercontent.com/62458770/155527327-46251dd6-ba2b-4422-a7a7-d875d0cf51a5.png)

**Comment by chanchann** [comment]
确确实实能够匹配成这样啊

**Comment by HzjFirst** [comment]
但是你注释里面那个current_path参数写的没有*啊？实际打印出来是有*的，不知道是不是我理解错了

**Comment by chanchann** [comment]
match*, 就是匹配以match为prefix点路径，比如match1234可以，match*1234也可以，同理matchHzjFirst，match*HzjFirst.
只要以match开头就行

**Comment by HzjFirst** [comment]
明白怎么用的了，谢谢啊
