### ISSUE TITLE
接口问题：这个接口不是太明白这个做什么用的？

### ISSUE THREAD

**Issue by HzjFirst** [wfrest/wfrest#108]
![image](https://user-images.githubusercontent.com/62458770/155527442-0812f551-2ac4-4bca-8c58-3b2cd20f988f.png)

**Comment by chanchann** [comment]
比如说 你传入路径是 /wildcast/HzjFirst, name就是HzjFirst，根据路径改变而去匹配这一段。
*就是 /wildcast/HzjFirst/actionHzjFirst 可以匹配， /wildcast/HzjFirst/action123 也可以匹配，是一种wildcast

**Comment by HzjFirst** [comment]
好的，理解了，谢谢啊
