### ISSUE TITLE
Segment fault after calling SeriesWork::cancel() in the task.

### ISSUE THREAD

**Issue by yuxilao** [wfrest/wfrest#113]
I'm trying to use the SeriesWork feature through the wfrest's interface like what 12_series_interface.cc shown.
When I call SeriesWork::cancel() in the HttpServer callback to interrupt the series,the program crash after calling SeriesWork::~Series().

This error might be caused by Router.cc line 56/59,you call series_of() to get SeriesWork object while it is actually not allocated.

**Comment by chanchann** [comment]
Hello, can you paste a demo here.

**Comment by yuxilao** [comment]
SORRY...I mess up the reason.

A very simple demo like this:
server.POST(url, [=](req,resp,series){
  series->cancel();
});

The real reason is that WFServerTask::done() has a deferred deletion which is called by the destructor of SeriesWork.
And when I call SeriesWork::cancel(),it delete the task immediately which cause duplicated deletion of WFServerTask.

Thanks for replying,I will post this issue to workflow.

**Comment by Barenboim** [comment]
https://github.com/sogou/workflow/pull/934
I am so sorry for this bug. Please update submodule.
@chanchann

**Comment by chanchann** [comment]
> The real reason is that WFServerTask::done() has a deferred deletion which is called by the destructor of SeriesWork. And when I call SeriesWork::cancel(),it delete the task immediately which cause duplicated deletion of WFServerTask.
> 
> Thanks

Ok, already update latest version.
