### ISSUE TITLE
Access IP Address

### ISSUE THREAD

**Issue by eternalvr** [wfrest/wfrest#116]
Is there any way to access the ip address of a request? It seems everything is private or not accessible (even with serieswork inside the handler)

**Comment by chanchann** [comment]
Currently you can do it like this : https://github.com/wfrest/wfrest/blob/main/example/24_peer_ip_address.cc

But I think I should design an easier api for users to get this kind of information.

**Comment by chanchann** [comment]
Already update this demo. Just use `http_task->peer_addr() / http_task->peer_port()`
