### ISSUE TITLE
优化

### ISSUE THREAD

**Issue by HzjFirst** [wfrest/wfrest#120]
workflow已经出了json工具，有没有计划把nlohmann替换掉？wrokflow的json工具也很好使

**Comment by Barenboim** [comment]
我觉得没必要😂nlohmann大多数人比较熟。

**Comment by Barenboim** [comment]
除非在workflow的那个上面再做一层封装。让用户法不多。

**Comment by chanchann** [comment]
因为workflow已经提供了，本来就可以直接使用，序列化发送即可

**Comment by Barenboim** [comment]
> 因为workflow已经提供了，本来就可以直接使用，序列化发送即可

能不能做个wfrest名称空间下的Json，引用workflow的c接口，然后用法和nlohmann一样。

**Comment by chanchann** [comment]
> > 因为workflow已经提供了，本来就可以直接使用，序列化发送即可
> 
> 能不能做个wfrest名称空间下的Json，引用workflow的c接口，然后用法和nlohmann一样。

👌好的

**Comment by HzjFirst** [comment]
对我也是这样想得，这样就不用nlohmann，直接使用wf的json了

**Comment by Barenboim** [comment]
这个功能已经做好了噢。

**Comment by HzjFirst** [comment]
好的，谢谢大佬，有时间我用一下
