### ISSUE TITLE
编译报错

### ISSUE THREAD

**Issue by henryw2019** [wfrest/wfrest#122]
今天下载wfrest代码，按照步骤执行make，报错：
in file included from src/core/BluePrint.inl: in member function wfrest::Blueprint::ROUTE…
165:31: error: expected ',' before '…' token
还有185行，305行，326行都有类似错误，请看看应该如何解决？

**Comment by chanchann** [comment]
https://github.com/wfrest/wfrest/discussions/74
编译器版本是多少

**Comment by henryw2019** [comment]
我的版本是4.8.5。  看来要升级才行咯，是否考虑兼容一下老编译器呢

**Comment by chanchann** [comment]
老编译器的话，实现变参会异常丑陋，可能就只能考虑阉割功能了
