### ISSUE TITLE
添加Save函数完成保存后的状态获取

### ISSUE THREAD

**Issue by JackyChen-Kuang** [wfrest/wfrest#128]
文件保存是异步的操作，有没有函数提供Save保存文件是否完成的函数呢？  
因为一般保存后需要使用该文件，不知道什么时候写完该文件还得自己去做判断
![image](https://user-images.githubusercontent.com/82799271/189802178-9fa490ea-7dce-4e30-93c9-568e322d100c.png)

**Comment by Barenboim** [comment]
感觉可以试试用切面。
或者可以给Save加一个回调，类似MySQL那样。

**Comment by chanchann** [comment]
Ok, 我加一个回调，把主动权也给用户暴露出来
如果要使用该文件，就再开一个task任务给他串到series后面，我们提供的高层api都是server_task的series

**Comment by JackyChen-Kuang** [comment]
> Ok, 我加一个回调，把主动权也给用户暴露出来 如果要使用该文件，就再开一个task任务给他串到series后面，我们提供的高层api都是server_task的series

感谢

**Comment by chanchann** [comment]
已经暴露了个回调，你目前的需求其实用不到，可以利用workflow的series串行机制就行了，后面的task肯定是你完成了写文件后的操作

**Comment by Barenboim** [comment]
现在这个接口不太好。改一下吧，参数表改成const struct FileIOArgs *而不是WFFileIOTask *。好像其它接口没有直接暴露workflow任务的。
