### ISSUE TITLE
first build cannot find “workflow/WFHttpServer.h”

### ISSUE THREAD

**Issue by kjiawei** [wfrest/wfrest#138]
/usr/local/include/wfrest/HttpServer.h:4:10: fatal error: workflow/WFHttpServer.h: 没有那个文件或目录

**Comment by chanchann** [comment]
git clone --recursive https://github.com/wfrest/wfrest
按照文档这样下载了第三方依赖了么，你这个是和workflow版本不匹配

**Comment by chanchann** [comment]
不推荐去链接你install的workflow

**Comment by chanchann** [comment]
请问问题解决了吗
