### ISSUE TITLE
解析json时，get（）自定义数据类型只能成功第一次。

### ISSUE THREAD

**Issue by checkman-shy** [wfrest/wfrest#149]
using kjson = nlohmann::json;
json data =req->json();

            try{
            auto register_info = data.get<RegisterInfo>();
        }catch(kjson::exception& ex){

            resp->Json(response_info);
            return;
        }

//以下error
         try{
            auto register_info = data.get<SubscribeInfo>();
        }catch(kjson::exception& ex){

            resp->Json(response_info);
            return;
        }

上述代码中RegisterInfo、SubscribeInfo是自定义的结构体。第一次调用get能够成功，

但是第二次调用会报错“get
还有 2 个重载

Simple extraction.

返回:
A character, or eof(). Tries to extract a character. If none are available, sets failbit and returns traits::eof().

没有与参数列表匹配的 重载函数 "nlohmann::basic_json<ObjectType, ArrayType, StringType, BooleanType, NumberIntegerType, NumberUnsignedType, NumberFloatType, AllocatorType, JSONSerializer, BinaryType>::get [其中 ObjectType=std::map, ArrayType=std::vector, StringType=std::__cxx11::string, BooleanType=bool, NumberIntegerType=int64_t, NumberUnsignedType=uint64_t, NumberFloatType=double, AllocatorType=std::allocator, JSONSerializer=nlohmann::adl_serializer, BinaryType=std::vector<uint8_t, std::allocator<uint8_t>>]”

**Comment by chanchann** [comment]
第二次是不是也应该auto register_info = data.get<RegisterInfo>();

**Comment by checkman-shy** [comment]
> 

是这样写的，但是报错了。try{
        auto register_info = data.get<RegisterInfo>();
    }catch(kjson::exception& ex){

        resp->Json(response_info);
        return;
    }
上面的可以，
下面的报错
try{
        auto register_info = data.get<SubscribeInfo>();
    }catch(kjson::exception& ex){

        resp->Json(response_info);
        return;
    }

**Comment by chanchann** [comment]
`auto register_info = data.get<RegisterInfo>();`

这markdown格式把 `<RegisterInfo>` 给吞了

**Comment by chanchann** [comment]
> `auto register_info = data.get<RegisterInfo>();`
> 
> 这markdown格式把 `<RegisterInfo>` 给吞了

我感觉我们交流的信息有点遗漏

**Comment by checkman-shy** [comment]
> > `auto register_info = data.get<RegisterInfo>();`
> > 这markdown格式把 `<RegisterInfo>` 给吞了
> 
> 我感觉我们交流的信息有点遗漏

请问那怎样获取到另一个自定义类型呢？

**Comment by chanchann** [comment]
> `auto register_info = data.get<RegisterInfo>();`
> 
> 这markdown格式把 `<RegisterInfo>` 给吞了

你的意思是不是，`data.get<RegisterInfo>()`成功，

**Comment by checkman-shy** [comment]
是的，后面编译不能通过

**Comment by chanchann** [comment]
https://github.com/nlohmann/json#arbitrary-types-conversions

对比下他的用法吧，具体信息你能不能抽象成一个文件来看看，我不知道你咋定义的struct
