### ISSUE TITLE
wfrest 关于内置json库如何生成这个结构，试了好久

### ISSUE THREAD

**Issue by ma-zhiqiang** [wfrest/wfrest#155]
![C`5`97STH1}X`O`H2N9J$~C](https://user-images.githubusercontent.com/60458644/227947869-c79d011c-ad7e-4da9-bc08-bff0386818b7.jpg)

主要是下面的这个data数据该如何生成，  试了好久，要么是 [], 要么就会发生Segmentation fault
1.
![image](https://user-images.githubusercontent.com/60458644/227948022-cf0294dd-3742-4879-8254-eb8aec7f1fb2.png)
2.
![image](https://user-images.githubusercontent.com/60458644/227948118-0f6e7054-f072-4bef-8982-8054e3467515.png)
3.
![image](https://user-images.githubusercontent.com/60458644/227948178-c38f7e94-d9a0-41e9-84f1-76ac737fc83b.png)

试了好久，  没试出我需要的这个结构，，，，，， 请大佬指点一下...

**Comment by ma-zhiqiang** [comment]
可以都放在data下吗？ data下面是一个数组， 现在已经可以放一个了，  但是如果放第二个时，跟我的预期有点出入
期望的效果
![image](https://user-images.githubusercontent.com/60458644/228077090-7fb361b9-85ca-4bf7-b543-1a0fce5cbd2c.png)
实际效果
![image](https://user-images.githubusercontent.com/60458644/228077240-a686e41b-2865-4f7b-a927-117cd151a406.png)

**Comment by chanchann** [comment]
<img width="538" alt="image" src="https://user-images.githubusercontent.com/27816166/228103447-598ce00b-bb86-4d30-8360-15bf167c3953.png">
<img width="893" alt="image" src="https://user-images.githubusercontent.com/27816166/228103481-5eaec4dc-a8cb-46d0-9766-484fa83dacfe.png">
