### ISSUE TITLE
代理服务器例子

### ISSUE THREAD

**Issue by ma-zhiqiang** [wfrest/wfrest#156]
wfrest是0.9.2版本 workflow是0.10.6版本
代码是代理服务器的例子，只加了一行打印，改了下端口
`#include "wfrest/HttpServer.h"
using namespace wfrest;

int main()
{
    HttpServer svr;

    svr.GET("/proxy", [](const HttpReq *req, HttpResp *resp){
        fprintf(stderr, "1111111");
        resp->Http("http://www.baidu.com");
    });

    if (svr.start(9001) == 0)
    {
        getchar();
        svr.stop();
    } else
    {
        fprintf(stderr, "Cannot start server");
        exit(1);
    }
    return 0;
}`

浏览器中访问， 然后尝试一直f5刷新， 然后出现了
free(): double free detected in tcache 2 
Aborted

**Comment by chanchann** [comment]
<img width="1156" alt="image" src="https://user-images.githubusercontent.com/27816166/234003747-39a85741-940b-4f42-bddf-f73b82b27096.png">
我这边么有复现出来，example里的demo不改动也会这样吗

**Comment by chanchann** [comment]
可以make check用valgrind跑一下，我这里valgrind也没检测出什么问题，
<img width="1038" alt="image" src="https://user-images.githubusercontent.com/27816166/234009914-2f5edcbe-4efd-4aaa-8fdf-f49c26f14174.png">

**Comment by ma-zhiqiang** [comment]
我这边又复现了一下，  点击刷新的同时去按F5会出现这个问题，  在打开F12的时候按F5进行刷新会出现这个问题
![image](https://user-images.githubusercontent.com/60458644/234228378-982553da-4a44-40bf-bb4b-f7f06965b1f3.png)
![image](https://user-images.githubusercontent.com/60458644/234228380-3780e385-71f1-416a-b275-d5f1c9bf2760.png)

**Comment by chanchann** [comment]
你先不手动link，先把example里的proxy编译出来会导致这个情况吗

**Comment by ma-zhiqiang** [comment]
![image](https://user-images.githubusercontent.com/60458644/234229367-07636166-f5e1-4134-9558-b8779ff2b2db.png)
感觉链接的没错

**Comment by ma-zhiqiang** [comment]
![image](https://user-images.githubusercontent.com/60458644/234230270-eb0918bc-3fd8-4c48-a698-a38e74996459.png)

**Comment by ma-zhiqiang** [comment]
valgrind -v --log-file=valgrind.log --tool=memcheck --leak-check=full --show-mismatched-frees=yes ./main
使用上面这个启动main程序，  没测试出来，     直接启动， 就会出现Bus error

**Comment by chanchann** [comment]
你是什么系统

**Comment by ma-zhiqiang** [comment]
ubuntu

**Comment by ma-zhiqiang** [comment]
Ubuntu

**Comment by chanchann** [comment]
什么版本的ubuntu

**Comment by ma-zhiqiang** [comment]
20.04的

**Comment by ma-zhiqiang** [comment]
佬， 我qq联系你了，  要不你上去瞅瞅

**Comment by chanchann** [comment]
你这是开的docker是吧，我感觉可能是docker的原因，https://www.escapelife.site/posts/43a2bb9b.html

**Comment by ma-zhiqiang** [comment]
没有安装docker
![image](https://user-images.githubusercontent.com/60458644/234239132-50ce1671-e80c-4246-a840-f71dda499179.png)

**Comment by ma-zhiqiang** [comment]
这服务器比较便宜
