### ISSUE TITLE
wfrest::HttpReq String方法返回中文字符串

### ISSUE THREAD

**Issue by ma-zhiqiang** [wfrest/wfrest#167]
使用 wfrest::HttpReq String方法返回中文字符串， 浏览器中访问，中文乱码
尝试使用 wfrest::HttpReq add_header_pair方法设置Content-Type 为text/plain; Charset=utf-8，浏览器正常显示中文，无乱码
我看到浏览器响应头里面有俩个Content-Type 的值，看了wfrest::HttpReq String方法，没看到有设置它的地方，这是怎么回事
![1685157234229](https://github.com/wfrest/wfrest/assets/60458644/5231814f-7395-4ea7-8643-780aa07f5dfd)

我尝试 wfrest::HttpReq Json 返回的中文字符串是正常，不需要额外设置Content-Type

**Comment by Barenboim** [comment]
试一下set_header_pair();

**Comment by ma-zhiqiang** [comment]
使用 set_header_pair，使用的Edge和Google测试还是存在俩个Content-Type

**Comment by chanchann** [comment]
设置的地方在
![image](https://github.com/wfrest/wfrest/assets/27816166/ac2f9591-d700-4c5e-a428-21731bcb6477)
你是resp->headers["Content-Type"] = xxx，这样用的吗，麻烦能够给出你的用法demo

**Comment by chanchann** [comment]
![image](https://github.com/wfrest/wfrest/assets/27816166/c76080a4-a858-4d24-9c20-e65c2c052d59)
![image](https://github.com/wfrest/wfrest/assets/27816166/e44b2099-ef84-4fb2-be5c-812e07e641a2)
写了个demo没问题

**Comment by ma-zhiqiang** [comment]
我使用的 add_header_pair和add_header_pair， 应该是我用法使用错误了

**Comment by ma-zhiqiang** [comment]
![image](https://github.com/wfrest/wfrest/assets/60458644/4b2e21da-05ab-40e5-ab7a-46abdde404b4)
你提供的方法是正确的，我尝试的方法存在问题，但也会添加Content-Type的值
