### ISSUE TITLE
wfrest中使用WFGraphTask 获取get_context是空

### ISSUE THREAD

**Issue by ma-zhiqiang** [wfrest/wfrest#168]
![image](https://github.com/wfrest/wfrest/assets/60458644/bac4f92d-c663-44f5-b84c-96951d037805)
![image](https://github.com/wfrest/wfrest/assets/60458644/f4f16620-4ed2-4006-9689-660153fdddfd)

图1，set_context
图2, 是WFGraphTask的第一个WFGraphNode 节点， 尝试获取context， 它是空的

**Comment by chanchann** [comment]
能不能截图完整一点，比如图一你的series在哪里获取，图二又是什么task

**Comment by chanchann** [comment]
![image](https://github.com/wfrest/wfrest/assets/27816166/79864fe7-844e-4a2b-be87-9da54eb11b92)
![image](https://github.com/wfrest/wfrest/assets/27816166/0e9db32e-77c5-4c95-bd92-0b46ac0299f0)
我写了个demo测试没问题

**Comment by ma-zhiqiang** [comment]
![image](https://github.com/wfrest/wfrest/assets/60458644/478e9d6d-db03-4eb6-b0ea-a55910d2fa80)
series是wfrest提供的(第三个参数)
图二中的任务是WFGraphTask，  通过它传建的WFGraphNode 节点， 构建图
![image](https://github.com/wfrest/wfrest/assets/60458644/0663fd2e-1dc0-4586-beb2-fe7bec7bab9a)

**Comment by ma-zhiqiang** [comment]
解决了， 原因是graph node和graph并不共享同一个serie
[https://github.com/sogou/workflow/issues/1285](url)
