### ISSUE TITLE
wfrest make fail

### ISSUE THREAD

**Issue by tangzhezhi** [wfrest/wfrest#170]
src/core/CMakeFiles/core.dir/build.make:192: recipe for target 'src/core/CMakeFiles/core.dir/HttpMsg.cc.o' failed
make[3]: *** [src/core/CMakeFiles/core.dir/HttpMsg.cc.o] Error 1
make[3]: Leaving directory '/home/tang/tools/wfrest/build.cmake'
CMakeFiles/Makefile2:342: recipe for target 'src/core/CMakeFiles/core.dir/all' failed
make[2]: *** [src/core/CMakeFiles/core.dir/all] Error 2
make[2]: Leaving directory '/home/tang/tools/wfrest/build.cmake'
Makefile:129: recipe for target 'all' failed
make[1]: *** [all] Error 2
make[1]: Leaving directory '/home/tang/tools/wfrest/build.cmake'
GNUmakefile:37: recipe for target 'install' failed
make: *** [install] Error 2

**Comment by chanchann** [comment]
麻烦能给更多信息吗，包括你什么系统，什么编译器，贴全一点编译信息，我这啥也看不出来

**Comment by tangzhezhi** [comment]
当前使用的是 ubuntu16.04做的编译，workflow是可以编译成功的，看到推荐了wfrest，就下载进行了编译，哈哈，你文档说了要 18.04以上，是不是这个原因？ 16.04和18.04是存在什么差异吗？ 编译器是用cmake3， gcc是5.4的版本。你写的依赖安装都安装了，最后报错就在 src/core/CMakeFiles/core.dir/build.make:192: recipe for target 'src/core/CMakeFiles/core.dir/HttpMsg.cc.o' failed，make 编译到这里就过不去了。 

最后谢谢你的回复。

**Comment by tangzhezhi** [comment]
补充一下：
![image](https://github.com/wfrest/wfrest/assets/5733504/4f783c58-192c-498b-bfcd-730a03e9fe7e)

**Comment by tangzhezhi** [comment]
> 麻烦能给更多信息吗，包括你什么系统，什么编译器，贴全一点编译信息，我这啥也看不出来

哈哈，看github你的readme里是支持 ubutun16.04的版本，但是我这里ubutun16.04确实编译报错，你试试看。
完全按照你的部署进行的，
cmake version 3.12.0
sudo apt-get install build-essential  zlib1g-dev libssl-dev libgtest-dev 
 git clone --recursive https://github.com/wfrest/wfrest 后进入 wfrest 进行 make命令。

**Comment by chanchann** [comment]
我按着你的这些配置环境复现出来了，拉最新的应该可以了
https://github.com/wfrest/wfrest/pull/175

**Comment by Barenboim** [comment]
> 我按着你的这些配置环境复现出来了，拉最新的应该可以了 #175

你可以重新release一下😂
