### ISSUE TITLE
Json使用不规范造成内存泄漏

### ISSUE THREAD

**Issue by 18328594608** [wfrest/wfrest#171]
您好，我现在使用了这里面的Json类。我在使用的过程中用到了Json类中的copy方法，现在我发现在copy之后造成了一定的内存泄漏，我想问下这个方法的正确使用规范是什么。

我目前的使用方式就是这样的的
Json deal_trade_record() {
    Json jsonRecord;
     *********
     **********
    return jsonRecord.copy();
}
我需要对这个返回回去的Json变量以及本身这个函数作用域内的Json变量手动释放么

**Comment by chanchann** [comment]
https://github.com/wfrest/wfrest/pull/172, valgrind测试已经没泄漏了
<img width="876" alt="image" src="https://github.com/wfrest/wfrest/assets/27816166/e5a6acb0-ffdc-46e8-b09d-244391f7e6b1">

**Comment by 18328594608** [comment]
ok 在pr合并之后我试一试。
