### ISSUE TITLE
query 不支持 array []

### ISSUE THREAD

**Issue by bayueqiankong** [wfrest/wfrest#180]
query不支持 array [] 的 字段查询
比如uri: http://localhost:25501/dev-api/api/v1/inquire/transactionSummary?pageNum=1&pageSize=10&industryChain[]=4&industryChain[]=7&industryChain[]=1&industryChain[]=2
其中，同样的 key键 industryChain 有多个 value值 ,
目前在 std::map<std::string, std::string> query_params_ 中 仅保存第一个 键值 ，且 key 健为 "industryChain[]" (而不是 ”industryChain“ )

可以增加 query 支持吗？

**Comment by chanchann** [comment]
查了下文档，这个好像不是http规范里的，这种是不是给个json的body更好

**Comment by Barenboim** [comment]
方括号应该不能在URL的path或query字段的吧。

**Comment by bayueqiankong** [comment]
> 查了下文档，这个好像不是http规范里的，这种是不是给个json的body更好
好的，当前在json，但用wfrest解析json格式req->json<nlohmann::json>() 需要的nlohmann::json版本（3.10.4 ）需要保持一致，原来我的项目里就已有版本（3.11.2）会和wfrest冲突，编译通过，链接失败

**Comment by Barenboim** [comment]
@bayueqiankong 你要不试试用wfrest::Json，这个比nlohmann快很多。

**Comment by bayueqiankong** [comment]
> @bayueqiankong 你要不试试用wfrest::Json，这个比nlohmann快很多。

已用，冲突已解决
