### ISSUE TITLE
内置集成的 Json 和 nlohmann Json 有什么关系？

### ISSUE THREAD

**Issue by yuancnnz** [wfrest/wfrest#188]
请问项目中使用的 Json 是依赖 workflow 的 Json吗？我看 src 目录中也有 nlohmann Json 的头文件，以及 example 目录中 json 的case 使用的也是 nlohmann Json。以及请问集成的 Json 性能有测试数据吗？

**Comment by yuancnnz** [comment]
十分感谢

**Comment by Barenboim** [comment]
我把示例也改成wfrest::Json了：https://github.com/wfrest/wfrest/pull/189
