### ISSUE TITLE
make check报错

### ISSUE THREAD

**Issue by WSY979666** [wfrest/wfrest#191]
请问make check的结果有这些错误是什么情况？
![image](https://github.com/wfrest/wfrest/assets/100759387/6b3d9b6d-d16a-44aa-900e-0c65112f95e1)

**Comment by chanchann** [comment]
看起来你valgrind没装，
![image](https://github.com/wfrest/wfrest/assets/27816166/512e846c-7f11-4250-9cf6-ca8a0d2d10ec)

**Comment by WSY979666** [comment]
> 

太感谢了佬，make check已成功！另外请问佬，这个项目应该从哪里开始入手看呀，或者有没有详细点的介绍，感觉码量好大，无从开始

**Comment by chanchann** [comment]
我感觉可以先把workflow耍熟悉一下，玩熟悉wf后，就知道他的接收回复流程了，我其实就是把wf的example拼起来了

**Comment by WSY979666** [comment]
佬学习workflow有啥推荐的渠道嘛，妈耶看到源码更被吓到了



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2023年8月5日(周六) 晚上10:56
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wfrest/wfrest] make check报错 (Issue #191)




 
我感觉可以先把workflow耍熟悉一下，玩熟悉wf后，就知道他的接收回复流程了，我其实就是把wf的example拼起来了

**Comment by chanchann** [comment]
> 佬学习workflow有啥推荐的渠道嘛，妈耶看到源码更被吓到了
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年8月5日(周六) 晚上10:56 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [wfrest/wfrest] make check报错 (Issue #191) 我感觉可以先把workflow耍熟悉一下，玩熟悉wf后，就知道他的接收回复流程了，我其实就是把wf的example拼起来了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

不用一开始就追求把源码看会，先把他把他用熟悉，他的设计理念，编程模式搞清楚，wfrest是进行二次开发，你就很容易看会代码了

**Comment by chanchann** [comment]
> 佬学习workflow有啥推荐的渠道嘛，妈耶看到源码更被吓到了
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2023年8月5日(周六) 晚上10:56 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [wfrest/wfrest] make check报错 (Issue #191) 我感觉可以先把workflow耍熟悉一下，玩熟悉wf后，就知道他的接收回复流程了，我其实就是把wf的example拼起来了 — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you authored the thread.Message ID: ***@***.***&gt;

推荐看看这个系列的zhihu，https://www.zhihu.com/people/liyingxin1412/posts
