### ISSUE TITLE
make failed

### ISSUE THREAD

**Issue by jstxcxb** [wfrest/wfrest#192]
os: centos 7.6.1810;    gcc:5.4.0;    cmake:3.10.0
Scanning dependencies of target core
make[3]: Leaving directory`/root/wfrest/build.cmake'
make[3]: Entering directory`/root/wfrest/build.cmake'
[ 4%] Building cxx object src/core/CMakeFiles/core.dir/BluePrint.cc.o
In file included from /root/wfrest/src/core/BluePrint.h:226:0,
from /root/wfrest/src/core/BluePrint.cc:1:
/root/wfrest/src/core/BluePrint.inl:In member function 'void wfrest::BluePrint::ROUTE(const string&,const Handler&, wfrest:iVerb, const AP& ...)’;
/root/wfrest/src/core/BluePrint.inl:165:31: error: expected ',’before '...’token
                      [handler, this, ap...](const HttpReq *req,
/root/wfrest/src/core/BluePrint.inl:165:31: error: expected identifier before '...’token
/root/wfrest/src/core/BluePrint.inl:165:34: error: parameter packs not expanded with '...’:
                      [handler, this, ap...](const HttpReq *req,
![1](https://github.com/wfrest/wfrest/assets/52713618/f46750b1-740d-49b3-9bd9-a787f53b0375)

**Comment by chanchann** [comment]
能把整个编译的内容贴全一下吗

**Comment by jstxcxb** [comment]
[make.log](https://github.com/wfrest/wfrest/files/12272852/make.log)

**Comment by jstxcxb** [comment]
which: no cmake3 in (/root/cmake-3.10.0-Linux-x86_64/bin:/home/hadoop/dp-scms/wfrest/cmake-3.10.0-Linux-x86_64/bin:/home/hadoop/dp-scms/wfrest/cmake-3.10.0-Linux-x86_64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin:/root/.local/bin:/root/hadoop/dp-scms/scripts:/root/hdtools)

make -C workflow

which: no cmake3 in (/root/cmake-3.10.0-Linux-x86_64/bin:/home/hadoop/dp-scms/wfrest/cmake-3.10.0-Linux-x86_64/bin:/home/hadoop/dp-scms/wfrest/cmake-3.10.0-Linux-x86_64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin:/root/.local/bin:/root/hadoop/dp-scms/scripts:/root/hdtools)

make[1]: Entering directory `/root/wfrest/workflow'

mkdir -p build.cmake

cd build.cmake && cmake -D CONSUL= -D KAFKA= -D MYSQL= -D REDIS= -D UPSTREAM= /root/wfrest/workflow

CMAKE_C_FLAGS_DEBUG is -g

CMAKE_C_FLAGS_RELEASE is -O3 -DNDEBUG

CMAKE_C_FLAGS_RELWITHDEBINFO is -O2 -g -DNDEBUG

CMAKE_C_FLAGS_MINSIZEREL is -Os -DNDEBUG

CMAKE_CXX_FLAGS_DEBUG is -g

CMAKE_CXX_FLAGS_RELEASE is -O3 -DNDEBUG

CMAKE_CXX_FLAGS_RELWITHDEBINFO is -O2 -g -DNDEBUG

CMAKE_CXX_FLAGS_MINSIZEREL is -Os -DNDEBUG

-- Configuring done

-- Generating done

-- Build files have been written to: /root/wfrest/workflow/build.cmake

make -C build.cmake -f Makefile

make[2]: Entering directory `/root/wfrest/workflow/build.cmake'

make[3]: Entering directory `/root/wfrest/workflow/build.cmake'

make[4]: Entering directory `/root/wfrest/workflow/build.cmake'

make[4]: Leaving directory `/root/wfrest/workflow/build.cmake'

make[4]: Entering directory `/root/wfrest/workflow/build.cmake'

make[4]: Leaving directory `/root/wfrest/workflow/build.cmake'

[  0%] Built target LINK_HEADERS

make[4]: Entering directory `/root/wfrest/workflow/build.cmake'

make[4]: Leaving directory `/root/wfrest/workflow/build.cmake'

[  5%] Built target client

make[4]: Entering directory `/root/wfrest/workflow/build.cmake'

make[4]: Leaving directory `/root/wfrest/workflow/build.cmake'

[ 25%] Built target kernel

make[4]: Entering directory `/root/wfrest/workflow/build.cmake'

make[4]: Leaving directory `/root/wfrest/workflow/build.cmake'

[ 32%] Built target util

make[4]: Entering directory `/root/wfrest/workflow/build.cmake'

make[4]: Leaving directory `/root/wfrest/workflow/build.cmake'

[ 39%] Built target manager

make[4]: Entering directory `/root/wfrest/workflow/build.cmake'

make[4]: Leaving directory `/root/wfrest/workflow/build.cmake'

[ 67%] Built target protocol

make[4]: Entering directory `/root/wfrest/workflow/build.cmake'

make[4]: Leaving directory `/root/wfrest/workflow/build.cmake'

[ 85%] Built target factory

make[4]: Entering directory `/root/wfrest/workflow/build.cmake'

make[4]: Leaving directory `/root/wfrest/workflow/build.cmake'

[ 92%] Built target nameservice

make[4]: Entering directory `/root/wfrest/workflow/build.cmake'

make[4]: Leaving directory `/root/wfrest/workflow/build.cmake'

[ 96%] Built target server

make[4]: Entering directory `/root/wfrest/workflow/build.cmake'

make[4]: Leaving directory `/root/wfrest/workflow/build.cmake'

[ 98%] Built target workflow-static

make[4]: Entering directory `/root/wfrest/workflow/build.cmake'

make[4]: Leaving directory `/root/wfrest/workflow/build.cmake'

[100%] Built target workflow-shared

make[3]: Leaving directory `/root/wfrest/workflow/build.cmake'

make[2]: Leaving directory `/root/wfrest/workflow/build.cmake'

make[1]: Leaving directory `/root/wfrest/workflow'

mkdir -p build.cmake

cd build.cmake && cmake /root/wfrest

-- Configuring done

-- Generating done

-- Build files have been written to: /root/wfrest/build.cmake

make -C build.cmake -f Makefile

make[1]: Entering directory `/root/wfrest/build.cmake'

make[2]: Entering directory `/root/wfrest/build.cmake'

make[3]: Entering directory `/root/wfrest/build.cmake'

make[3]: Leaving directory `/root/wfrest/build.cmake'

make[3]: Entering directory `/root/wfrest/build.cmake'

make[3]: Leaving directory `/root/wfrest/build.cmake'

[  0%] Built target LINK_HEADERS

make[3]: Entering directory `/root/wfrest/build.cmake'

make[3]: Leaving directory `/root/wfrest/build.cmake'

make[3]: Entering directory `/root/wfrest/build.cmake'

[  4%] Building CXX object src/core/CMakeFiles/core.dir/BluePrint.cc.o

In file included from /root/wfrest/src/core/BluePrint.h:226:0,

                 from /root/wfrest/src/core/BluePrint.cc:1:

/root/wfrest/src/core/BluePrint.inl: In member function ‘void wfrest::BluePrint::ROUTE(const string&, const Handler&, wfrest::Verb, const AP& ...)’:

/root/wfrest/src/core/BluePrint.inl:165:31: error: expected ‘,’ before ‘...’ token

             [handler, this, ap...](const HttpReq *req,

                               ^

/root/wfrest/src/core/BluePrint.inl:165:31: error: expected identifier before ‘...’ token

/root/wfrest/src/core/BluePrint.inl:165:34: error: parameter packs not expanded with ‘...’:

             [handler, this, ap...](const HttpReq *req,

                                  ^

/root/wfrest/src/core/BluePrint.inl:165:34: note:         ‘ap’

/root/wfrest/src/core/BluePrint.inl: In member function ‘void wfrest::BluePrint::ROUTE(const string&, int, const Handler&, wfrest::Verb, const AP& ...)’:

/root/wfrest/src/core/BluePrint.inl:185:49: error: expected ‘,’ before ‘...’ token

             [handler, compute_queue_id, this, ap...](HttpReq *req,

                                                 ^

/root/wfrest/src/core/BluePrint.inl:185:49: error: expected identifier before ‘...’ token

/root/wfrest/src/core/BluePrint.inl:185:52: error: parameter packs not expanded with ‘...’:

             [handler, compute_queue_id, this, ap...](HttpReq *req,

                                                    ^

/root/wfrest/src/core/BluePrint.inl:185:52: note:         ‘ap’

/root/wfrest/src/core/BluePrint.inl: In member function ‘void wfrest::BluePrint::ROUTE(const string&, const SeriesHandler&, wfrest::Verb, const AP& ...)’:

/root/wfrest/src/core/BluePrint.inl:305:31: error: expected ‘,’ before ‘...’ token

             [handler, this, ap...](const HttpReq *req,

                               ^

/root/wfrest/src/core/BluePrint.inl:305:31: error: expected identifier before ‘...’ token

/root/wfrest/src/core/BluePrint.inl:305:34: error: parameter packs not expanded with ‘...’:

             [handler, this, ap...](const HttpReq *req,

                                  ^

/root/wfrest/src/core/BluePrint.inl:305:34: note:         ‘ap’

/root/wfrest/src/core/BluePrint.inl: In member function ‘void wfrest::BluePrint::ROUTE(const string&, int, const SeriesHandler&, wfrest::Verb, const AP& ...)’:

/root/wfrest/src/core/BluePrint.inl:326:49: error: expected ‘,’ before ‘...’ token

             [handler, compute_queue_id, this, ap...](HttpReq *req,

                                                 ^

/root/wfrest/src/core/BluePrint.inl:326:49: error: expected identifier before ‘...’ token

/root/wfrest/src/core/BluePrint.inl:326:52: error: parameter packs not expanded with ‘...’:

             [handler, compute_queue_id, this, ap...](HttpReq *req,

                                                    ^

/root/wfrest/src/core/BluePrint.inl:326:52: note:         ‘ap’

make[3]: *** [src/core/CMakeFiles/core.dir/BluePrint.cc.o] Error 1

make[3]: Leaving directory `/root/wfrest/build.cmake'

make[2]: *** [src/core/CMakeFiles/core.dir/all] Error 2

make[2]: Leaving directory `/root/wfrest/build.cmake'

make[1]: *** [all] Error 2

make[1]: Leaving directory `/root/wfrest/build.cmake'

make: *** [all] Error 2

**Comment by chanchann** [comment]
make clean后再make的log贴出来看看呢

**Comment by jstxcxb** [comment]
which: no cmake3 in (/root/cmake-3.10.0-Linux-x86_64/bin:/home/hadoop/dp-scms/wfrest/cmake-3.10.0-Linux-x86_64/bin:/home/hadoop/dp-scms/wfrest/cmake-3.10.0-Linux-x86_64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin:/root/.local/bin:/root/hadoop/dp-scms/scripts:/root/hdtools)

make -C workflow

which: no cmake3 in (/root/cmake-3.10.0-Linux-x86_64/bin:/home/hadoop/dp-scms/wfrest/cmake-3.10.0-Linux-x86_64/bin:/home/hadoop/dp-scms/wfrest/cmake-3.10.0-Linux-x86_64/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/root/bin:/root/.local/bin:/root/hadoop/dp-scms/scripts:/root/hdtools)

make[1]: Entering directory `/root/wfrest/workflow'

mkdir -p build.cmake

cd build.cmake && cmake -D CONSUL= -D KAFKA= -D MYSQL= -D REDIS= -D UPSTREAM= /root/wfrest/workflow

-- The C compiler identification is GNU 4.8.5

-- The CXX compiler identification is GNU 4.8.5

-- Check for working C compiler: /usr/bin/cc

-- Check for working C compiler: /usr/bin/cc -- works

-- Detecting C compiler ABI info

-- Detecting C compiler ABI info - done

-- Detecting C compile features

-- Detecting C compile features - done

-- Check for working CXX compiler: /usr/bin/c++

-- Check for working CXX compiler: /usr/bin/c++ -- works

-- Detecting CXX compiler ABI info

-- Detecting CXX compiler ABI info - done

-- Detecting CXX compile features

-- Detecting CXX compile features - done

CMAKE_C_FLAGS_DEBUG is -g

CMAKE_C_FLAGS_RELEASE is -O3 -DNDEBUG

CMAKE_C_FLAGS_RELWITHDEBINFO is -O2 -g -DNDEBUG

CMAKE_C_FLAGS_MINSIZEREL is -Os -DNDEBUG

CMAKE_CXX_FLAGS_DEBUG is -g

CMAKE_CXX_FLAGS_RELEASE is -O3 -DNDEBUG

CMAKE_CXX_FLAGS_RELWITHDEBINFO is -O2 -g -DNDEBUG

CMAKE_CXX_FLAGS_MINSIZEREL is -Os -DNDEBUG

-- Found OpenSSL: /usr/lib64/libcrypto.so (found version "1.0.2k") 

-- Configuring done

-- Generating done

-- Build files have been written to: /root/wfrest/workflow/build.cmake

make -C build.cmake -f Makefile

make[2]: Entering directory `/root/wfrest/workflow/build.cmake'

make[3]: Entering directory `/root/wfrest/workflow/build.cmake'

make[4]: Entering directory `/root/wfrest/workflow/build.cmake'

Scanning dependencies of target LINK_HEADERS

make[4]: Leaving directory `/root/wfrest/workflow/build.cmake'

make[4]: Entering directory `/root/wfrest/workflow/build.cmake'

make[4]: Leaving directory `/root/wfrest/workflow/build.cmake'

[  0%] Built target LINK_HEADERS

make[4]: Entering directory `/root/wfrest/workflow/build.cmake'

Scanning dependencies of target client

make[4]: Leaving directory `/root/wfrest/workflow/build.cmake'

make[4]: Entering directory `/root/wfrest/workflow/build.cmake'

[  1%] Building CXX object src/client/CMakeFiles/client.dir/WFDnsClient.cc.o

[  3%] Building CXX object src/client/CMakeFiles/client.dir/WFMySQLConnection.cc.o

[  5%] Building CXX object src/client/CMakeFiles/client.dir/WFConsulClient.cc.o

make[4]: Leaving directory `/root/wfrest/workflow/build.cmake'

[  5%] Built target client

make[4]: Entering directory `/root/wfrest/workflow/build.cmake'

Scanning dependencies of target kernel

make[4]: Leaving directory `/root/wfrest/workflow/build.cmake'

make[4]: Entering directory `/root/wfrest/workflow/build.cmake'

[  7%] Building CXX object src/kernel/CMakeFiles/kernel.dir/IOService_linux.cc.o

[  8%] Building C object src/kernel/CMakeFiles/kernel.dir/mpoller.c.o

[ 10%] Building C object src/kernel/CMakeFiles/kernel.dir/poller.c.o

[ 12%] Building C object src/kernel/CMakeFiles/kernel.dir/rbtree.c.o

[ 14%] Building C object src/kernel/CMakeFiles/kernel.dir/msgqueue.c.o

[ 16%] Building C object src/kernel/CMakeFiles/kernel.dir/thrdpool.c.o

[ 17%] Building CXX object src/kernel/CMakeFiles/kernel.dir/CommRequest.cc.o

[ 19%] Building CXX object src/kernel/CMakeFiles/kernel.dir/CommScheduler.cc.o

/root/wfrest/workflow/src/kernel/CommScheduler.cc: In member function ‘virtual CommTarget* CommSchedGroup::acquire(int)’:

/root/wfrest/workflow/src/kernel/CommScheduler.cc:442:9: warning: ‘target’ may be used uninitialized in this function [-Wmaybe-uninitialized]

  return target;

         ^

[ 21%] Building CXX object src/kernel/CMakeFiles/kernel.dir/Communicator.cc.o

In file included from /root/wfrest/workflow/src/kernel/Communicator.cc:37:0:

/root/wfrest/workflow/src/kernel/mpoller.h: In member function ‘void Communicator::handle_listen_result(poller_result*)’:

/root/wfrest/workflow/src/kernel/mpoller.h:52:57: warning: ‘timeout’ may be used uninitialized in this function [-Wmaybe-uninitialized]

  return poller_add(data, timeout, mpoller->poller[index]);

                                                         ^

/root/wfrest/workflow/src/kernel/Communicator.cc:1006:6: note: ‘timeout’ was declared here

  int timeout;

      ^

[ 23%] Building CXX object src/kernel/CMakeFiles/kernel.dir/Executor.cc.o

[ 25%] Building CXX object src/kernel/CMakeFiles/kernel.dir/SubTask.cc.o

make[4]: Leaving directory `/root/wfrest/workflow/build.cmake'

[ 25%] Built target kernel

make[4]: Entering directory `/root/wfrest/workflow/build.cmake'

Scanning dependencies of target util

make[4]: Leaving directory `/root/wfrest/workflow/build.cmake'

make[4]: Entering directory `/root/wfrest/workflow/build.cmake'

[ 26%] Building C object src/util/CMakeFiles/util.dir/json_parser.c.o

[ 28%] Building CXX object src/util/CMakeFiles/util.dir/EncodeStream.cc.o

[ 30%] Building CXX object src/util/CMakeFiles/util.dir/StringUtil.cc.o

[ 32%] Building CXX object src/util/CMakeFiles/util.dir/URIParser.cc.o

make[4]: Leaving directory `/root/wfrest/workflow/build.cmake'

[ 32%] Built target util

make[4]: Entering directory `/root/wfrest/workflow/build.cmake'

Scanning dependencies of target manager

make[4]: Leaving directory `/root/wfrest/workflow/build.cmake'

make[4]: Entering directory `/root/wfrest/workflow/build.cmake'

[ 33%] Building CXX object src/manager/CMakeFiles/manager.dir/DnsCache.cc.o

[ 35%] Building CXX object src/manager/CMakeFiles/manager.dir/RouteManager.cc.o

[ 37%] Building CXX object src/manager/CMakeFiles/manager.dir/WFGlobal.cc.o

[ 39%] Building CXX object src/manager/CMakeFiles/manager.dir/UpstreamManager.cc.o

make[4]: Leaving directory `/root/wfrest/workflow/build.cmake'

[ 39%] Built target manager

make[4]: Entering directory `/root/wfrest/workflow/build.cmake'

Scanning dependencies of target protocol

make[4]: Leaving directory `/root/wfrest/workflow/build.cmake'

make[4]: Entering directory `/root/wfrest/workflow/build.cmake'

[ 41%] Building CXX object src/protocol/CMakeFiles/protocol.dir/PackageWrapper.cc.o

[ 42%] Building CXX object src/protocol/CMakeFiles/protocol.dir/SSLWrapper.cc.o

/root/wfrest/workflow/src/protocol/SSLWrapper.cc: In member function ‘virtual int protocol::SSLHandshaker::append(const void*, size_t*)’:

/root/wfrest/workflow/src/protocol/SSLWrapper.cc:114:17: warning: value computed is not used [-Wunused-value]

  BIO_reset(wbio);

                 ^

/root/wfrest/workflow/src/protocol/SSLWrapper.cc:122:18: warning: value computed is not used [-Wunused-value]

   BIO_reset(wbio);

                  ^

/root/wfrest/workflow/src/protocol/SSLWrapper.cc: In member function ‘virtual int protocol::SSLWrapper::append(const void*, size_t*)’:

/root/wfrest/workflow/src/protocol/SSLWrapper.cc:227:17: warning: value computed is not used [-Wunused-value]

  BIO_reset(wbio);

                 ^

/root/wfrest/workflow/src/protocol/SSLWrapper.cc: In member function ‘virtual int protocol::SSLWrapper::feedback(const void*, size_t)’:

/root/wfrest/workflow/src/protocol/SSLWrapper.cc:261:18: warning: value computed is not used [-Wunused-value]

   BIO_reset(wbio);

                  ^

/root/wfrest/workflow/src/protocol/SSLWrapper.cc: In member function ‘virtual int protocol::ServerSSLWrapper::append(const void*, size_t*)’:

/root/wfrest/workflow/src/protocol/SSLWrapper.cc:279:17: warning: value computed is not used [-Wunused-value]

  BIO_reset(wbio);

                 ^

/root/wfrest/workflow/src/protocol/SSLWrapper.cc:286:18: warning: value computed is not used [-Wunused-value]

   BIO_reset(wbio);

                  ^

[ 44%] Building C object src/protocol/CMakeFiles/protocol.dir/dns_parser.c.o

[ 46%] Building CXX object src/protocol/CMakeFiles/protocol.dir/DnsMessage.cc.o

[ 48%] Building CXX object src/protocol/CMakeFiles/protocol.dir/DnsUtil.cc.o

[ 50%] Building C object src/protocol/CMakeFiles/protocol.dir/http_parser.c.o

[ 51%] Building CXX object src/protocol/CMakeFiles/protocol.dir/HttpMessage.cc.o

[ 53%] Building CXX object src/protocol/CMakeFiles/protocol.dir/HttpUtil.cc.o

[ 55%] Building C object src/protocol/CMakeFiles/protocol.dir/mysql_stream.c.o

[ 57%] Building C object src/protocol/CMakeFiles/protocol.dir/mysql_parser.c.o

[ 58%] Building C object src/protocol/CMakeFiles/protocol.dir/mysql_byteorder.c.o

[ 60%] Building CXX object src/protocol/CMakeFiles/protocol.dir/MySQLMessage.cc.o

[ 62%] Building CXX object src/protocol/CMakeFiles/protocol.dir/MySQLResult.cc.o

[ 64%] Building CXX object src/protocol/CMakeFiles/protocol.dir/MySQLUtil.cc.o

[ 66%] Building C object src/protocol/CMakeFiles/protocol.dir/redis_parser.c.o

[ 67%] Building CXX object src/protocol/CMakeFiles/protocol.dir/RedisMessage.cc.o

make[4]: Leaving directory `/root/wfrest/workflow/build.cmake'

[ 67%] Built target protocol

make[4]: Entering directory `/root/wfrest/workflow/build.cmake'

Scanning dependencies of target factory

make[4]: Leaving directory `/root/wfrest/workflow/build.cmake'

make[4]: Entering directory `/root/wfrest/workflow/build.cmake'

[ 69%] Building CXX object src/factory/CMakeFiles/factory.dir/WFGraphTask.cc.o

[ 71%] Building CXX object src/factory/CMakeFiles/factory.dir/DnsTaskImpl.cc.o

[ 73%] Building CXX object src/factory/CMakeFiles/factory.dir/WFTaskFactory.cc.o

[ 75%] Building CXX object src/factory/CMakeFiles/factory.dir/Workflow.cc.o

[ 76%] Building CXX object src/factory/CMakeFiles/factory.dir/HttpTaskImpl.cc.o

[ 78%] Building CXX object src/factory/CMakeFiles/factory.dir/WFResourcePool.cc.o

[ 80%] Building CXX object src/factory/CMakeFiles/factory.dir/WFMessageQueue.cc.o

[ 82%] Building CXX object src/factory/CMakeFiles/factory.dir/FileTaskImpl.cc.o

[ 83%] Building CXX object src/factory/CMakeFiles/factory.dir/MySQLTaskImpl.cc.o

[ 85%] Building CXX object src/factory/CMakeFiles/factory.dir/RedisTaskImpl.cc.o

make[4]: Leaving directory `/root/wfrest/workflow/build.cmake'

[ 85%] Built target factory

make[4]: Entering directory `/root/wfrest/workflow/build.cmake'

Scanning dependencies of target nameservice

make[4]: Leaving directory `/root/wfrest/workflow/build.cmake'

make[4]: Entering directory `/root/wfrest/workflow/build.cmake'

[ 87%] Building CXX object src/nameservice/CMakeFiles/nameservice.dir/WFNameService.cc.o

[ 89%] Building CXX object src/nameservice/CMakeFiles/nameservice.dir/WFDnsResolver.cc.o

[ 91%] Building CXX object src/nameservice/CMakeFiles/nameservice.dir/WFServiceGovernance.cc.o

[ 92%] Building CXX object src/nameservice/CMakeFiles/nameservice.dir/UpstreamPolicies.cc.o

make[4]: Leaving directory `/root/wfrest/workflow/build.cmake'

[ 92%] Built target nameservice

make[4]: Entering directory `/root/wfrest/workflow/build.cmake'

Scanning dependencies of target server

make[4]: Leaving directory `/root/wfrest/workflow/build.cmake'

make[4]: Entering directory `/root/wfrest/workflow/build.cmake'

[ 94%] Building CXX object src/server/CMakeFiles/server.dir/WFServer.cc.o

[ 96%] Building CXX object src/server/CMakeFiles/server.dir/WFMySQLServer.cc.o

make[4]: Leaving directory `/root/wfrest/workflow/build.cmake'

[ 96%] Built target server

make[4]: Entering directory `/root/wfrest/workflow/build.cmake'

Scanning dependencies of target workflow-static

make[4]: Leaving directory `/root/wfrest/workflow/build.cmake'

make[4]: Entering directory `/root/wfrest/workflow/build.cmake'

[ 98%] Linking CXX static library ../../_lib/libworkflow.a

make[4]: Leaving directory `/root/wfrest/workflow/build.cmake'

[ 98%] Built target workflow-static

make[4]: Entering directory `/root/wfrest/workflow/build.cmake'

Scanning dependencies of target workflow-shared

make[4]: Leaving directory `/root/wfrest/workflow/build.cmake'

make[4]: Entering directory `/root/wfrest/workflow/build.cmake'

[100%] Linking CXX shared library ../../_lib/libworkflow.so

make[4]: Leaving directory `/root/wfrest/workflow/build.cmake'

[100%] Built target workflow-shared

make[3]: Leaving directory `/root/wfrest/workflow/build.cmake'

make[2]: Leaving directory `/root/wfrest/workflow/build.cmake'

make[1]: Leaving directory `/root/wfrest/workflow'

mkdir -p build.cmake

cd build.cmake && cmake /root/wfrest

-- The C compiler identification is GNU 4.8.5

-- The CXX compiler identification is GNU 4.8.5

-- Check for working C compiler: /usr/bin/cc

-- Check for working C compiler: /usr/bin/cc -- works

-- Detecting C compiler ABI info

-- Detecting C compiler ABI info - done

-- Detecting C compile features

-- Detecting C compile features - done

-- Check for working CXX compiler: /usr/bin/c++

-- Check for working CXX compiler: /usr/bin/c++ -- works

-- Detecting CXX compiler ABI info

-- Detecting CXX compiler ABI info - done

-- Detecting CXX compile features

-- Detecting CXX compile features - done

-- Found OpenSSL: /usr/lib64/libcrypto.so (found version "1.0.2k") 

-- Configuring done

-- Generating done

-- Build files have been written to: /root/wfrest/build.cmake

make -C build.cmake -f Makefile

make[1]: Entering directory `/root/wfrest/build.cmake'

make[2]: Entering directory `/root/wfrest/build.cmake'

make[3]: Entering directory `/root/wfrest/build.cmake'

Scanning dependencies of target LINK_HEADERS

make[3]: Leaving directory `/root/wfrest/build.cmake'

make[3]: Entering directory `/root/wfrest/build.cmake'

make[3]: Leaving directory `/root/wfrest/build.cmake'

[  0%] Built target LINK_HEADERS

make[3]: Entering directory `/root/wfrest/build.cmake'

Scanning dependencies of target core

make[3]: Leaving directory `/root/wfrest/build.cmake'

make[3]: Entering directory `/root/wfrest/build.cmake'

[  4%] Building CXX object src/core/CMakeFiles/core.dir/BluePrint.cc.o

In file included from /root/wfrest/src/core/BluePrint.h:226:0,

                 from /root/wfrest/src/core/BluePrint.cc:1:

/root/wfrest/src/core/BluePrint.inl: In member function ‘void wfrest::BluePrint::ROUTE(const string&, const Handler&, wfrest::Verb, const AP& ...)’:

/root/wfrest/src/core/BluePrint.inl:165:31: error: expected ‘,’ before ‘...’ token

             [handler, this, ap...](const HttpReq *req,

                               ^

/root/wfrest/src/core/BluePrint.inl:165:31: error: expected identifier before ‘...’ token

/root/wfrest/src/core/BluePrint.inl:165:34: error: parameter packs not expanded with ‘...’:

             [handler, this, ap...](const HttpReq *req,

                                  ^

/root/wfrest/src/core/BluePrint.inl:165:34: note:         ‘ap’

/root/wfrest/src/core/BluePrint.inl: In member function ‘void wfrest::BluePrint::ROUTE(const string&, int, const Handler&, wfrest::Verb, const AP& ...)’:

/root/wfrest/src/core/BluePrint.inl:185:49: error: expected ‘,’ before ‘...’ token

             [handler, compute_queue_id, this, ap...](HttpReq *req,

                                                 ^

/root/wfrest/src/core/BluePrint.inl:185:49: error: expected identifier before ‘...’ token

/root/wfrest/src/core/BluePrint.inl:185:52: error: parameter packs not expanded with ‘...’:

             [handler, compute_queue_id, this, ap...](HttpReq *req,

                                                    ^

/root/wfrest/src/core/BluePrint.inl:185:52: note:         ‘ap’

/root/wfrest/src/core/BluePrint.inl: In member function ‘void wfrest::BluePrint::ROUTE(const string&, const SeriesHandler&, wfrest::Verb, const AP& ...)’:

/root/wfrest/src/core/BluePrint.inl:305:31: error: expected ‘,’ before ‘...’ token

             [handler, this, ap...](const HttpReq *req,

                               ^

/root/wfrest/src/core/BluePrint.inl:305:31: error: expected identifier before ‘...’ token

/root/wfrest/src/core/BluePrint.inl:305:34: error: parameter packs not expanded with ‘...’:

             [handler, this, ap...](const HttpReq *req,

                                  ^

/root/wfrest/src/core/BluePrint.inl:305:34: note:         ‘ap’

/root/wfrest/src/core/BluePrint.inl: In member function ‘void wfrest::BluePrint::ROUTE(const string&, int, const SeriesHandler&, wfrest::Verb, const AP& ...)’:

/root/wfrest/src/core/BluePrint.inl:326:49: error: expected ‘,’ before ‘...’ token

             [handler, compute_queue_id, this, ap...](HttpReq *req,

                                                 ^

/root/wfrest/src/core/BluePrint.inl:326:49: error: expected identifier before ‘...’ token

/root/wfrest/src/core/BluePrint.inl:326:52: error: parameter packs not expanded with ‘...’:

             [handler, compute_queue_id, this, ap...](HttpReq *req,

                                                    ^

/root/wfrest/src/core/BluePrint.inl:326:52: note:         ‘ap’

make[3]: *** [src/core/CMakeFiles/core.dir/BluePrint.cc.o] Error 1

make[3]: Leaving directory `/root/wfrest/build.cmake'

make[2]: *** [src/core/CMakeFiles/core.dir/all] Error 2

make[2]: Leaving directory `/root/wfrest/build.cmake'

make[1]: *** [all] Error 2

make[1]: Leaving directory `/root/wfrest/build.cmake'

make: *** [all] Error 2

**Comment by Barenboim** [comment]
Gcc 5.0 or above is required!

**Comment by chanchann** [comment]
<img width="884" alt="image" src="https://github.com/wfrest/wfrest/assets/27816166/825e79cf-68bd-408d-bfe0-8b34ac48a412">
