### ISSUE TITLE
请问上传文件是否支持一个回调函数？ 

### ISSUE THREAD

**Issue by tangzhezhi** [wfrest/wfrest#198]
在操作文件上传后，
直接使用 这个方法是可以成功的，resp->Save(path, std::move(fileinfo.second)); 

但是我如果想在后面继续对这个上传的文件进行下一步操作的时候，没办法直接使用这个文件，是否可以在save方法里提供一个回调函数？ 或者是我没有理解你的这个方法的使用呢。

期待你的回复，谢谢。

**Comment by Barenboim** [comment]
这里有一个啊：https://github.com/wfrest/wfrest/blob/3e91b699df31bbb96c67bc6691147b62ddb81cfa/src/core/HttpMsg.h#L215

**Comment by Barenboim** [comment]
甚至有例子：
https://github.com/wfrest/wfrest/blob/3e91b699df31bbb96c67bc6691147b62ddb81cfa/example/07_file_save.cc#L44

**Comment by tangzhezhi** [comment]
> 甚至有例子：
> 
> https://github.com/wfrest/wfrest/blob/3e91b699df31bbb96c67bc6691147b62ddb81cfa/example/07_file_save.cc#L44

thank you .

**Comment by tangzhezhi** [comment]
自己补充一下回调函数的使用，便于新手遇到我同样的问题：
如下使用即可：
                 resp->Save(path, std::move(fileinfo.second),[path,resp](const struct FileIOArgs* args) {
                        // fprintf(stderr, "%s/n", static_cast<const char *>(args->buf));
                         fprintf(stderr, "%s/n", path);
                         std::cout <<  "FileIOArgs path : " << path << std::endl;
                    });
