### ISSUE TITLE
About multi cookies reading

### ISSUE THREAD

**Issue by borrypaula88** [wfrest/wfrest#203]
Thank U for so much,WFREST is a powerful and useful project!
I've wrote multi cookies to the browser,however,I can't get the true values when I try to read them,for e.g.:
/*
        cookie.set_key("user")
            .set_value("chanchan")
            .set_path("/")
                .set_http_only(true);
        resp->add_cookie(std::move(cookie));
        HttpCookie cookie2;
        cookie2.set_key("tk")//jwt
            .set_value(token);
        resp->add_cookie(std::move(cookie2));
        resp->set_status(HttpStatusOK);
        resp->String("Login success");
*/
It worked well。Then:
/*   svr.GET("/home", [](const HttpReq *req, HttpResp *resp)
    {
        const std::string &cookie_val = req->cookie("user");
        if(cookie_val != "chanchan")
        {
            resp->set_status(HttpStatusUnauthorized);
                Json json;
                json["error"] = "Unauthorized";
                json["user"] = cookie_val;//Here 
                resp->Json(json);
            } else
        {
            resp->set_status(HttpStatusOK);
            const std::string &token = req->cookie("tk");
            std::string rsa_pub_key = R"(-----BEGIN PUBLIC KEY-----
*/
The response I get in the browser is like this: {"error":"Unauthorized","user":"chanchan; tk"}

**Comment by borrypaula88** [comment]
/*
        cookie.set_key("user")
            .set_value("chanchan")
            .set_path("/")
                .set_http_only(true);
        resp->add_cookie(std::move(cookie));
        HttpCookie cookie2;
        cookie2.set_key("tk")//jwt
            .set_value(token);
        resp->add_cookie(std::move(cookie2));
        resp->set_status(HttpStatusOK);
        resp->String("Login success");
*/
It worked well。Then:
/*   svr.GET("/home", [](const HttpReq *req, HttpResp *resp)
    {
        const std::string &cookie_val = req->cookie("user");
        if(cookie_val != "chanchan")
        {
            resp->set_status(HttpStatusUnauthorized);
                Json json;
                json["error"] = "Unauthorized";
                json["user"] = cookie_val;//Here 
                resp->Json(json);
            } else
        {
            resp->set_status(HttpStatusOK);
            const std::string &token = req->cookie("tk");
            std::string rsa_pub_key = R"(-----BEGIN PUBLIC KEY-----
*/
The response I get in the browser is like this: {"error":"Unauthorized","user":"chanchan; tk"}

**Comment by chanchann** [comment]
<img width="1333" alt="image" src="https://github.com/wfrest/wfrest/assets/27816166/e076e448-280d-4205-a654-c2f02e11e3ea">
Please open the F12 Developer Tools and inspect the cookies sent by the browser.

**Comment by chanchann** [comment]
In rfc document, it seems that you can set multiple lines of set-cookie from server to user agent, but when the user agent generates an HTTP request, the user agent MUST NOT attach more than one Cookie header field. So you need check http header first.

**Comment by borrypaula88** [comment]
Thank you very much! This is the request headers of then browser:
![reh](https://github.com/wfrest/wfrest/assets/145536050/efc55d11-1fae-45a4-a193-7a42aba3d8ec)

If I  try:
json["tk"] = req->cookie("tk");

And it's empty:
{"error":"Unauthorized","user":"chanchan; tk","tk":""}

**Comment by chanchann** [comment]
It combines two cookies into one line, you can split it with ';'.
It seems that different browser use different strategy.

**Comment by borrypaula88** [comment]
OK.Thank you very much!
