### ISSUE TITLE
JSON 出现内存泄露

### ISSUE THREAD

**Issue by 18328594608** [wfrest/wfrest#205]
Json::Array json_data = JsonArr(json, "data");
            for (auto data:json_data) {
            
    代码这么写的情况下, for (auto data:json_data) 这句话出现内存泄露.
这样子去调用json的迭代器访问时出现了malloc 但是没有对应的delete

**Comment by chanchann** [comment]
lib里没有JsonArr(json, "data");这个用法吧

**Comment by 18328594608** [comment]
> lib里没有JsonArr(json, "data");这个用法吧

这个是我自己写的一个宏函数,里面实现是这样的:
const Json::Array& GetJsonArr(const Json& value,std::string key)
{
    Json::Array json;
    if(value.is_valid())
    {
        if(value[key].is_valid() && value[key].is_array())
        {
            return json = value[key].get<Json::Array>();;
        }
    }
    return json.copy();
}

出现问题的地方是 for (auto data:json_data) 这段代码 在执行的时候出现内存泄露.使用valgrind 有报错

**Comment by chanchann** [comment]
麻烦给个能跑的demo，这里面还有你自己实现的函数，我没办法排查问题

**Comment by 18328594608** [comment]
我自己写了个单测用例没发现泄露 估计是i自己实现的代码问题 这个isu我先关掉了
