### ISSUE TITLE
[BUG] Empty JSON Response in HttpResp::MySQL on main Branch

### ISSUE THREAD

**Issue by Lee-side** [wfrest/wfrest#206]
### 感谢

首先，我想对项目的作者表示由衷的感谢！我接触cpp的时间并不长，如果我的问题存在浅薄的认识，我先表示抱歉。 
### 问题描述
克隆并测试项目的 main 分支时遇到了一个问题，调用执行HttpResp::MySQL 后返回的JSON 是空的。v0.9.3 稳定版本不存在这个问题，猜测是使用新的Json的库的问题。

### 环境信息
- 操作系统：ubuntu22.04
- 编译版本： g++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
- 项目版本：commit 93b84cb7e85fb279b7cf449d558b5a7bd3c0accf

### 复现步骤
1. 运行 ./example/21_mysql
2. 请求 GET http://localhost:8888/mysql0
3. 观察到返回的Json 是 {}

### 相关代码
```c++ 
// example/21_mysql.cc 23,26
svr.GET("/mysql0", [](const HttpReq *req, HttpResp *resp)
{
    resp->MySQL("mysql://root:123456@localhost", "SHOW DATABASES");
});
```
### 猜测问题

1. 我通过打印发现,push_back执行过后 resut_set并没有放入到json 中.
```c++
//  src/core/HttpMsg.cc 213
json["result_set"].push_back(result_set);
```

2. can_arr_push_back是结果是false 
```c++
// src/base/Json.cc 643
void Json::push_back(const Json& val)
{
    if (!can_arr_push_back())
    {
        return;
    }
    json_array_t* arr = json_value_array(node_);
    Json copy_json = val;
    json_array_append(arr, 0, copy_json.node_);
    copy_json.reset();
}
```
3.  is_root的结果是 false is_null 的结果是true ,导致并不能将json转换成array
```c++
bool Json::can_arr_push_back()
{
    if (is_root() && is_null())
    {
        to_array();
    }
    return is_array();
}
```

### Thanks

Firstly, I would like to express my sincere gratitude to the project's author! I haven't been working with C++ for long, and if there are any misunderstandings in my questions, I apologize in advance.

### Issue Description

I encountered an issue while cloning and testing the main branch of the project. After calling `HttpResp::MySQL`, the returned JSON is empty. This issue is not present in the stable version v0.9.3, and I suspect it may be related to the use of the new JSON library.

### Environment Information

- Operating System: Ubuntu 22.04
- Compiler Version: g++ (Ubuntu 11.4.0-1ubuntu1~22.04) 11.4.0
- Project Version: Commit 93b84cb7e85fb279b7cf449d558b5a7bd3c0accf

### Reproduction Steps

1. Run `./example/21_mysql`
2. Make a GET request to `http://localhost:8888/mysql0`
3. Observe that the returned JSON is {}

### Relevant Code

```c++
// example/21_mysql.cc 23,26
svr.GET("/mysql0", [](const HttpReq *req, HttpResp *resp)
{
    resp->MySQL("mysql://root:123456@localhost", "SHOW DATABASES");
});
```
### Speculation on the Issue
1. Upon printing, I noticed that after push_back, the result_set is not placed into the JSON.
```c++
//  src/core/HttpMsg.cc 213
json["result_set"].push_back(result_set);
```

2. `can_arr_push_back` returns false as a result.
```c++
// src/base/Json.cc 643
void Json::push_back(const Json& val)
{
    if (!can_arr_push_back())
    {
        return;
    }
    json_array_t* arr = json_value_array(node_);
    Json copy_json = val;
    json_array_append(arr, 0, copy_json.node_);
    copy_json.reset();
}
```
3.  The result of `is_root` is false, and the result of `is_null` is true, causing the JSON not to be converted to an array.
```c++
bool Json::can_arr_push_back()
{
    if (is_root() && is_null())
    {
        to_array();
    }
    return is_array();
}
```

**Comment by Barenboim** [comment]
所以感觉这个问题和workflow的关系不大对吧。可能是换了默认JSON的原因。@chanchann

**Comment by Barenboim** [comment]
我找到原因了，wfrest::Json的问题。我改改试试。

**Comment by chanchann** [comment]
可以暂时先用
```cpp
Json js;
Json arr;
arr.push_back(1);
arr.push_back(2);
js.push_back("arr", arr);
```
这种写法，目前operator[]暂时不支持，需要花时间重构下

**Comment by Barenboim** [comment]
有这么难吗？你看一下我这个最新PR：https://github.com/wfrest/Json/pull/63

**Comment by Barenboim** [comment]
~~~cpp
#include <iostream>
#include "Json.h"

using namespace wfrest;

int main()
{
    Json json;
    Json json1(1);
    json["1"] = "test";
    json["2"] = "hello";
    json["3"].push_back(Json::Object({{"55", 2}}));
    json["3"].push_back("bbbbbb");
    json["3"].push_back("cccccc");
    json["4"]["5"]["6"] = "bbbb";
    json["5"].push_back("xxxx", 1);
    json["5"].push_back("pi", 3.14);
    json["6"].push_back("arr", { "1", "2", "3" });
    std::cout << json.dump() << std::endl;
    return 0;
}
~~~
这个case可以通过。不过这代码确实需要重构一下，问题不少。而且我相信现在的实现不是最优的。

**Comment by Barenboim** [comment]
@Lee-side 你好，最新PR已经修复了这个问题。麻烦试一下：https://github.com/wfrest/wfrest/pull/208

**Comment by Lee-side** [comment]
感谢! 最新的代码 HttpResp::MySQL可以正常返回JSON数据了。
