### ISSUE TITLE
无法显示svg图片

### ISSUE THREAD

**Issue by jianbaoshan** [wfrest/wfrest#212]
![image](https://github.com/wfrest/wfrest/assets/38252454/a07945d9-3636-4b35-b065-3a9b7c76309b)

svg图片的解析方式是svg+xml

**Comment by chanchann** [comment]
https://www.w3.org/TR/SVG/mimereg.html
可以看下这里，SVG 使用 XML 格式定义图像

**Comment by jianbaoshan** [comment]
谢谢
