### ISSUE TITLE
http://192.168.21.31:7777/test/1这种最后一个数字的范围是1-20，可以只注册一个http请求吗

### ISSUE THREAD

**Issue by jianbaoshan** [wfrest/wfrest#214]
下面多个url可以只注册一次请求吗

* http://192.168.21.31:7777/test/1
* http://192.168.21.31:7777/test/2
* http://192.168.21.31:7777/test/3

**Comment by chanchann** [comment]
可以看看这个example，https://github.com/wfrest/wfrest/blob/main/example/02_parameter_path.cc
<img width="927" alt="image" src="https://github.com/wfrest/wfrest/assets/27816166/b4199225-dc37-430f-a1d0-3eb9acf982cd">
/test/{num}

**Comment by jianbaoshan** [comment]
好的 谢谢
