### ISSUE TITLE
json处理http.content_length=0的时候导致程序挂掉

### ISSUE THREAD

**Issue by jianbaoshan** [wfrest/wfrest#216]
http的post请求抓包
![image](https://github.com/wfrest/wfrest/assets/38252454/152acf89-314a-4aef-b20b-0af98bf3f083)

代码执行req_data = req->json();会导致程序挂掉
![image](https://github.com/wfrest/wfrest/assets/38252454/7c546506-4fc6-4b0b-bfa1-97709924e4af)

请问一下 这里要如何处理才能避免程序挂掉

**Comment by jianbaoshan** [comment]
代码截图更新
![image](https://github.com/wfrest/wfrest/assets/38252454/e836cbbc-58b0-466f-a974-cc03d57b537c)

**Comment by Barenboim** [comment]
奇怪，我怎么没有找到HttpReq::json()这个函数的实现在哪里。

**Comment by Barenboim** [comment]
应该不难改。明天看一下。

**Comment by chanchann** [comment]
已经修复，麻烦拉最新代码试试

**Comment by jianbaoshan** [comment]
谢谢  最新代码已经没有问题了
