### ISSUE TITLE
json判断成员是否存在导致程序挂掉

### ISSUE THREAD

**Issue by jianbaoshan** [wfrest/wfrest#218]
url请求如下
![image](https://github.com/wfrest/wfrest/assets/38252454/71d04670-db46-4780-b139-fd1bf8f35af1)

daim代码执行json.has("xxxx")导致程序挂掉，期望的不是挂掉，而是返回不存在
![image](https://github.com/wfrest/wfrest/assets/38252454/af6a2d41-3d1b-4aec-b7e3-452f147d0429)

**Comment by Barenboim** [comment]
这个我来改一下。好像没有先判断root是否是object。

**Comment by Barenboim** [comment]
https://github.com/wfrest/wfrest/pull/220

**Comment by jianbaoshan** [comment]
json使用出错的时候  可以不会导致程序挂掉吗  而是报错

**Comment by Barenboim** [comment]
是的啊，我修改了，你拉一下最新代码试一试。
最新代码在不是object的时候返回false。看上面那个PR。

**Comment by jianbaoshan** [comment]
好的 谢谢  我拉取一下看看
