### ISSUE TITLE
有响应验证通过的客户端的url请求的功能吗

### ISSUE THREAD

**Issue by jianbaoshan** [wfrest/wfrest#219]
有很多客户端 但是只有输入的用户名和密码通过验证之后 wfrest才响应验证通过的客户端的url请求 至于对应其他没有验证通过的客户端不响应

**Comment by Barenboim** [comment]
> 有很多客户端 但是只有输入的用户名和密码通过验证之后 wfrest才响应验证通过的客户端的url请求 至于对应其他没有验证通过的客户端不响应

试一下task_of(resp)->noreply()，可以不回复直接关闭连接。

**Comment by Barenboim** [comment]
我觉得，可以直接给resp加个NoReply()接口。我写写看。

**Comment by Barenboim** [comment]
@jianbaoshan 你先试试task_of(resp)->noreply()能不能解决你的问题吧。
