### ISSUE TITLE
解析json文件出错

### ISSUE THREAD

**Issue by jianbaoshan** [wfrest/wfrest#222]
解析json文件，可以正确得到json数组的大小，但是有些操作会导致程序挂掉，下图红框中的操作都会导致程序挂掉
![image](https://github.com/wfrest/wfrest/assets/38252454/3fba0389-c317-43e5-aa63-5db8bd7b6553)

json文件内容如下：
![image](https://github.com/wfrest/wfrest/assets/38252454/cc3930d6-b013-4e0a-ae41-5a47a95b6519)

麻烦帮忙看看是什么原因  谢谢

**Comment by Barenboim** [comment]
你写成：Json file_json就没有问题。Array那个类应该不是给外部用的吧？

**Comment by jianbaoshan** [comment]
非常感谢  确实是这里不对导致的
