### ISSUE TITLE
web server端可以从客户端的请求中得到ip吗

### ISSUE THREAD

**Issue by jianbaoshan** [wfrest/wfrest#225]
http://172.17.2.169:7777/otn/system/config-download   比如这个请求  可以在服务端得到172.17.2.169这个IP吗

**Comment by Barenboim** [comment]
得到client的IP吧？

**Comment by jianbaoshan** [comment]
服务器的IP

**Comment by Barenboim** [comment]
服务器自己的IP，你可以想办法自己传进去吧？另外，server启动之后，可以通过get_listen_addr得到自己监听的socket地址，这个函数在WFServerBase里。
https://github.com/sogou/workflow/blob/0cfc31b4452279d0bf99386dd59a84322b62ea4c/src/server/WFServer.h#L153

**Comment by jianbaoshan** [comment]
是的  可以得到服务器的IP  我想了解一下 wfrest这边有没有比较简单的方式得到服务器的IP

**Comment by Barenboim** [comment]
get_listen_addr这个函数的接口定义类似于系统函数getsockname。用起来略微麻烦。我们可以加一个接口来支持一下。

**Comment by Barenboim** [comment]
这个我来搞一下吧。

**Comment by jianbaoshan** [comment]
好的 非常感谢  http://172.17.2.169:7777/otn/system/config-download  我的想法是否可以做到解析这个URL的参数这种方式来得到这个IP

**Comment by Barenboim** [comment]
啊，这个就很简单了啊。就是header里的host域。你在request header里找一下就可以了。

**Comment by jianbaoshan** [comment]
好的 我试试  谢谢

**Comment by Barenboim** [comment]
Header里有一项Host: 172.17.2.169:7777 的，你看一下这个取header的方法：https://github.com/wfrest/wfrest/blob/main/docs/cn/header.md

**Comment by jianbaoshan** [comment]
谢谢 我试试
