### ISSUE TITLE
resp->Save接口保存文件执行结束的时候，不能立马检查到该文件的存在

### ISSUE THREAD

**Issue by jianbaoshan** [wfrest/wfrest#226]
Save保存的文件好像是请求结束才会出现，是否可以在执行完Save操作之后就能检查到该文件的存在呢，下图是等了1分钟之后才出现文件的
![image](https://github.com/wfrest/wfrest/assets/38252454/acc6fceb-6ec3-4981-b1e8-47a4386bd187)

**Comment by Barenboim** [comment]
resp里所有这些大写开头的方法（String, Save, MySQL, Sleep等等），理论上都是函数的最后一行，不要再在后面加东西。如果需要，应该用另外一个多一个回调的接口。在那里你应该可以得到操作的结果。

**Comment by jianbaoshan** [comment]
好的  谢谢

**Comment by jianbaoshan** [comment]
我看了一下这个有回调接口的Save函数，FileIOrgs这个结构体是读写存储的文件接口 我需要的是文件已经保存到设备上的  然后来解压文件进行操作的 这个接口不能满足我的需求   看来只能先保存文件 然后再调用另外一个接口来解压缩文件然后执行后续其他操作了

**Comment by Barenboim** [comment]
> 我看了一下这个有回调接口的Save函数，FileIOrgs这个结构体是读写存储的文件接口 我需要的是文件已经保存到设备上的 然后来解压文件进行操作的 这个接口不能满足我的需求 看来只能先保存文件 然后再调用另外一个接口来解压缩文件然后执行后续其他操作了

我不太理解你的具体需求。回调函数返回Save的结果，这时候文件已经保存好了。Save函数式异步的，只有到了回调才确保文件已经保存完毕。

你第一个图的方法，永远也看不到文件存在，因为Save只是想series里添加了一个写文件任务，调用它的函数结束，写文件操作才开始执行。

**Comment by jianbaoshan** [comment]
我的需求是执行完Save之后 文件要保存到设备上 然后我发命令给另外一个程序  让它去处理这个报错的文件

**Comment by Barenboim** [comment]
> 我的需求是执行完Save之后 文件要保存到设备上 然后我发命令给另外一个程序 让它去处理这个报错的文件

这个可能可以用一下AOP吧：https://github.com/wfrest/wfrest/blob/main/docs/cn/aop.md
