### ISSUE TITLE
使用表单数据会导致程序挂掉

### ISSUE THREAD

**Issue by jianbaoshan** [wfrest/wfrest#233]
下图红框中的表单赋值操作会导致程序挂掉，麻烦帮忙看看， 谢谢

![image](https://github.com/wfrest/wfrest/assets/38252454/a2d4f16f-000d-4ae7-80d3-2df60c6789f9)

![image](https://github.com/wfrest/wfrest/assets/38252454/bab0526b-efb0-412f-8865-b7678e9e91ae)

**Comment by Barenboim** [comment]
最好写成这样：
const Form &form = req->form();
这个地方为什么能编译通过我看一下，可能是没有继承uncopyable。

**Comment by Barenboim** [comment]
最好写成这样：
~~~cpp
const Form &form = req->form();
~~~
但我看到Form是这么定义的：
~~~cpp
using Form = std::map<std::string, std::pair<std::string, std::string>>;
~~~
所以按理这里是会实现复制的，程序挂掉不应该。

**Comment by Barenboim** [comment]
我怀疑是生命周期问题。你可以贴一下你的调用链。这里怎么看都不应该会挂。

**Comment by jianbaoshan** [comment]
const Form &form = req->form(); 这种操作也试过  还是一样会导致程序挂掉


1、第一步
![image](https://github.com/wfrest/wfrest/assets/38252454/11b0258a-b266-4c32-855d-aedde03d0cb3)

2、第二步
![image](https://github.com/wfrest/wfrest/assets/38252454/80f810c8-90f4-4a15-b25b-515530ae7daa)

3、第三步
![image](https://github.com/wfrest/wfrest/assets/38252454/979af518-1a9c-487d-8f9b-f8aa2c00114e)


4、第四步
![image](https://github.com/wfrest/wfrest/assets/38252454/b3aef99f-de88-4c20-aacb-76ceeb3705a3)

**Comment by jianbaoshan** [comment]
1、程序启动第一次执行成功，第二次就会导致程序挂掉，下图是连续执行2次的日志和相关代码
![image](https://github.com/wfrest/wfrest/assets/38252454/66c0eecc-e1c3-448d-a4c5-c3f7823e765e)
![image](https://github.com/wfrest/wfrest/assets/38252454/4e1ab5c1-1091-43aa-9376-38fceaa97cf4)

**Comment by Barenboim** [comment]
这个我需要看一下。我不知道wfrest能不能在循环里调用多次Save。我觉得你应该是在Save的回调里再Save下一个，最后一个的回调里调用Json。
wfrest里这些resp->Xxxxx()的接口，理论上应该是链式使用的。

**Comment by Barenboim** [comment]
我又瞅了一眼源代码，你这么写的确是不对的，一个函数里不应该调用两次resp->Xxxxx()。

你要保存多个文件，需要这个接口：
~~~cpp
void Save(const std::string &file_dst, std::string &&content,
              const HttpFile::FileIOArgsFunc &func);
~~~
在func，调用下一个Save()或Json()。

**Comment by jianbaoshan** [comment]
今天又测试了一下，还是不行，即使一次只调用一次Save  还是会导致程序挂掉
![image](https://github.com/wfrest/wfrest/assets/38252454/9d497a29-68a3-45c3-b2bb-c23ec1a4813d)
![image](https://github.com/wfrest/wfrest/assets/38252454/4137b8a6-84cc-4a29-a2c7-3301d7322a98)

**Comment by Barenboim** [comment]
有程序崩掉时的堆栈信息吗？

**Comment by jianbaoshan** [comment]
你们复现不出来这个问题吗？  堆栈信息要等会

**Comment by Barenboim** [comment]
form这个调用，可以说是被用得最多的。如果有问题早就发现了。而且，这个调用只是简单返回req里的一个map的引用，很难有问题。






---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月27日(周四) 中午1:32
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wfrest/wfrest] 使用表单数据会导致程序挂掉 (Issue #233)




 
你们复现不出来这个问题吗？  堆栈信息要等会

**Comment by jianbaoshan** [comment]
程序挂掉了，都没有捕获到这些信号
![image](https://github.com/wfrest/wfrest/assets/38252454/c69ce6b8-d104-4f75-a3fd-5d039e3e0fe6)

**Comment by jianbaoshan** [comment]
捕获了这么多信号，都没有看到任何信息，挂的悄无声息
![image](https://github.com/wfrest/wfrest/assets/38252454/cfd14d3e-4a1a-460d-88a0-5e6524f279cf)

**Comment by jianbaoshan** [comment]
找到问题了，传文件太耗内存了，我传一个大小42.8M的文件，168M的内存居然不够用导致出现OOM。下图2888的下一个内存大小就是这个程序挂掉释放内存之后的大小。这个有办法解决吗，太夸张了。
![image](https://github.com/wfrest/wfrest/assets/38252454/116e2b27-9f9f-4a6a-b76d-6eb153b5dd25)

**Comment by Barenboim** [comment]
目前这个http server，是传输完成再调用你的hander的。

不过，我们确实也有一些可以优化内存的地方，目前，我们缓存区不够是直接double了，你42MB的文件，应该remalloc是分配了64MB，然后加上之前的32MB确实有可能OOM。

你也可以分开上传。

**Comment by jianbaoshan** [comment]
现在是分开了还是不行，程序第一次启动分开2次传2个文件可以成功，但是内存使用太夸张了
![image](https://github.com/wfrest/wfrest/assets/38252454/4bf9ac30-4d53-4e83-b2c7-8e0229ea3cfd)
<img width="58" alt="8fa488e6d318a35caec12e1f9cbca72" src="https://github.com/wfrest/wfrest/assets/38252454/b01eca97-0c6b-4d54-b463-36be7445bef2">

再传一次文件就会出现内存不够了导致程序挂掉了
![image](https://github.com/wfrest/wfrest/assets/38252454/30603ff9-fc8d-4689-a823-fcfb02dd8fb0)
![image](https://github.com/wfrest/wfrest/assets/38252454/a6e85b1b-fd9c-4237-accd-d82c736514a2)

**Comment by jianbaoshan** [comment]
我刚才试了一下分2次传2个1K大小的文件，完全没有问题。传大文件你们这里的处理有问题，能不能改为少申请点内存而多花点时间来传文件呢

**Comment by Barenboim** [comment]
> 我刚才试了一下分2次传2个1K大小的文件，完全没有问题。传大文件你们这里的处理有问题，能不能改为少申请点内存而多花点时间来传文件呢

我们现在的消息都是保存在内存中的，你是说中间结果也用磁盘来保存？

**Comment by jianbaoshan** [comment]
我传了2个10M大小的文件，传了2次之后，一共传了40M的大小。设备的可用内存几乎没了，看起来内存被占用没有及时释放掉
![image](https://github.com/wfrest/wfrest/assets/38252454/66cf04c1-1117-4f0f-b564-467ff3018ba6)

**Comment by Barenboim** [comment]
内存不是这么看的……

你要看进程的RSS占用。你这个图，都是buff/cache，这个是文件系统缓存。内存只要没有被利用，都会被文件系统拿来当缓存。

另外，为什么现在还有内存这么小的机子？

**Comment by Barenboim** [comment]
你看一进程的内存吧。

**Comment by jianbaoshan** [comment]
当前RSS是157M了
root     20696  0.6 33.2 1991416 157344 ?      Ssl  16:30   0:04 /var/run/product/OTN6000R/bin/WebLCT -d

**Comment by jianbaoshan** [comment]
我把这个WebLCT杀掉之后 ，立马就好了
![image](https://github.com/wfrest/wfrest/assets/38252454/0dee59c4-fb1c-4805-95a1-d6c6f898552e)

**Comment by Barenboim** [comment]
内存不是泄露，你多传几次10M的文件吧，看看内存有没有持续增涨。

**Comment by jianbaoshan** [comment]
1、刚启动，没有进行任何传文件操作
![image](https://github.com/wfrest/wfrest/assets/38252454/e47ab286-ef1d-44d7-8422-47c7b11aa639)

2、第一次传了2个10M大小的文件
![image](https://github.com/wfrest/wfrest/assets/38252454/4199480b-c052-4ec7-a0f5-bce8b5c2ecb9)

3、第二次传了2个10M大小的文件
![image](https://github.com/wfrest/wfrest/assets/38252454/67d07b2d-a0f6-42f5-baba-a4b456b1a3c1)

4、没有第四次了，再传2个10m大小的文件，肯定出现OOM导致程序挂掉

**Comment by Barenboim** [comment]
前面的两次，都回复完成了是吧？这个有点奇怪。我看一下代码。

**Comment by jianbaoshan** [comment]
是的 都完成了，文件也传到设备上了

**Comment by Barenboim** [comment]
我这边看的话，暂时看不出有内存泄露的地方。但传几个10MB的文件把100多MB内存打爆确实有点奇怪了。你那边是否能用valgrind之前的工具，帮我们看看程序正常结果时，有没有内存泄露呢？

**Comment by Barenboim** [comment]
我这边试了，是没有内存泄露的。我用大文件再试一下。

**Comment by Barenboim** [comment]
传10MB的文件，内存确实会增加很快，会到200多MB。不过没有内存泄露。我看看能不能优化。

**Comment by jianbaoshan** [comment]
多传几次呢，是不是会一直增加导致系统没有可用的内存而导致程序挂掉

**Comment by jianbaoshan** [comment]
除了传文件这里你们使用了remalloc操作。看看是不是还有其他地方也这样操作了，只是其他地方申请的内存比较少而不明显，但是如果长时间运行使用的话，积累下来也会出现这种情况的。

**Comment by Barenboim** [comment]
> 除了传文件这里你们使用了remalloc操作。看看是不是还有其他地方也这样操作了，只是其他地方申请的内存比较少而不明显，但是如果长时间运行使用的话，积累下来也会出现这种情况的。

我看了，不是workflow层的问题。是C++ STL把内存用上去的。如果只把消息收下来，内存非常稳定。但只要调用一下req->body()，然后正常结束，内存就可能涨到快200MB。我想想有什么办法。

**Comment by Barenboim** [comment]
@jianbaoshan 
也不是C++的问题，是标准库会为每个线程建立内存区，你内存太少，不应该开那么多线程。你在程序开头加上这几行就可以了：
~~~cpp
int main()
{
    WFGlobalSettings settings = GLOBAL_SETTINGS_DEFAULT;
    settings.poller_threads = 1;
    settings.handler_threads = 1;
    WORKFLOW_library_init(&settings);
    ...
}
~~~

**Comment by Barenboim** [comment]
你这点内存，为什么要传这么大的文件。。。
都会有overhead的。你内存要控制这么紧，可能直接用workflow好一点，可以不在handler里复制body内容。





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月27日(周四) 晚上6:54
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wfrest/wfrest] 使用表单数据会导致程序挂掉 (Issue #233)




 
传2个10M文件，可以多次传，而且RSS的大小先增加再减少，但是传42M的文件还是会占用很大内存导致程序挂掉。
 image.png (view on web)

**Comment by jianbaoshan** [comment]
空闲内存有170M左右，传个42M的文件都不够 这个不行吧

**Comment by jianbaoshan** [comment]
> 你这点内存，为什么要传这么大的文件。。。 都会有overhead的。你内存要控制这么紧，可能直接用workflow好一点，可以不在handler里复制body内容。
> […](#)
> ---原始邮件--- 发件人: ***@***.***&gt; 发送时间: 2024年6月27日(周四) 晚上6:54 收件人: ***@***.***&gt;; 抄送: ***@***.******@***.***&gt;; 主题: Re: [wfrest/wfrest] 使用表单数据会导致程序挂掉 (Issue #233) 传2个10M文件，可以多次传，而且RSS的大小先增加再减少，但是传42M的文件还是会占用很大内存导致程序挂掉。 image.png (view on web) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

我看看怎么使用workflow传文件，有相关的例子吗？

**Comment by Barenboim** [comment]
你是没用过别的框架吧，我们已经是极致省内存了。这些内存是多线程引起的，不是我们能控制。


虽然我不知道为什么你只有100多M内存，然后还要传这么大的消息。但你用workflow里的接口，是可以再把内存省下去一些的。不用多一次拷贝。





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年6月27日(周四) 晚上7:11
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wfrest/wfrest] 使用表单数据会导致程序挂掉 (Issue #233)




 
空闲内存有170M左右，传个42M的文件都不够 这个不行吧

**Comment by Barenboim** [comment]
> > 你这点内存，为什么要传这么大的文件。。。 都会有overhead的。你内存要控制这么紧，可能直接用workflow好一点，可以不在handler里复制body内容。
> > […](#)
> > ---原始邮件--- 发件人: _**@**_._**> 发送时间: 2024年6月27日(周四) 晚上6:54 收件人: _**@**_.**_>; 抄送: _**@**_._**_**@**_.**_>; 主题: Re: [wfrest/wfrest] 使用表单数据会导致程序挂掉 (Issue #233) 传2个10M文件，可以多次传，而且RSS的大小先增加再减少，但是传42M的文件还是会占用很大内存导致程序挂掉。 image.png (view on web) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: _**@**_.***>
> 
> 我看看怎么使用workflow传文件，有相关的例子吗？

先用带series参数的POST接口，handler里用req->get_parsed_body()可以无复制得到原始的http body。然后自己解析出内容，用WFTaskFactory::create_pwrite_task()来产生写磁盘任务，放到series里。

不过，如果你对性能没有什么特别需求，也直接调用pwrite写磁盘。

总之很多解析的工作需要自己做，减少内存申请释放。

**Comment by jianbaoshan** [comment]
好的  谢谢
