### ISSUE TITLE
蓝图可以级联吗？

### ISSUE THREAD

**Issue by wangyongxiao** [wfrest/wfrest#234]
蓝图可以级联吗？

比如第一级蓝图是 path1 
第二级是path2
这样组合起来就是 /path1/path2/...

我还可以在第二级分支一下 path3
这样就是 /path1/path3/...

可以支持到这个特性吗

**Comment by chanchann** [comment]
example是不是就是你要的级联:  https://github.com/wfrest/wfrest/tree/main/example/14_blue_print
```
inline void set_admin_bp(BluePrint &bp)
{
    bp.GET("/test1/", [](const HttpReq *req, HttpResp *resp)
    {
        fprintf(stderr, "New page\n");
    });

    bp.GET("/test2", [](const HttpReq *req, HttpResp *resp)
    {
        fprintf(stderr, "Edit page\n");
    });
}

int main()
{
    signal(SIGINT, sig_handler);

    HttpServer svr;
    
    svr.POST("/page/{uri}", [](const HttpReq *req, HttpResp *resp)
    {
        fprintf(stderr, "Blog Page\n");
    });

    BluePrint admin_bp;
    set_admin_bp(admin_bp);
    
    svr.register_blueprint(admin_bp, "/path1");
   // ...
```

**Comment by wangyongxiao** [comment]
> example是不是就是你要的级联: https://github.com/wfrest/wfrest/tree/main/example/14_blue_print
> 
> ```
> inline void set_admin_bp(BluePrint &bp)
> {
>     bp.GET("/test1/", [](const HttpReq *req, HttpResp *resp)
>     {
>         fprintf(stderr, "New page\n");
>     });
> 
>     bp.GET("/test2", [](const HttpReq *req, HttpResp *resp)
>     {
>         fprintf(stderr, "Edit page\n");
>     });
> }
> 
> int main()
> {
>     signal(SIGINT, sig_handler);
> 
>     HttpServer svr;
>     
>     svr.POST("/page/{uri}", [](const HttpReq *req, HttpResp *resp)
>     {
>         fprintf(stderr, "Blog Page\n");
>     });
> 
>     BluePrint admin_bp;
>     set_admin_bp(admin_bp);
>     
>     svr.register_blueprint(admin_bp, "/path1");
>    // ...
> ```

我使用add_blueprint接口实现了我想要的需求，谢谢
