### ISSUE TITLE
有一个小问题，应该算bug吧

### ISSUE THREAD

**Issue by sgfcz** [wfrest/wfrest#236]
在util/mysqlutil里面，不能初始化之后再push_back,这样vector就是两倍的长度，并且有一半是空字符
只能在for里面用i索引传值，要不然就不要初始化为标题头长度

**Comment by Barenboim** [comment]
会多占一些空间？

**Comment by sgfcz** [comment]
> 会多占一些空间？

不是多占空间的问题
比如你的方法是拿到所有表头然后放在std::vector<std::string>里面是吧，表头有三个字段，a、b、c
但是这个vector会返回{“”，“”，“”，“a”，“b”，“c”}

**Comment by chanchann** [comment]
我这里初始化有问题，我应该reserve

**Comment by sgfcz** [comment]
> [0823e5b](https://github.com/wfrest/wfrest/commit/0823e5bbb6048e68495e43c2a4f4d797308fb2a4) 已修复，麻烦你再看看


cool
