### ISSUE TITLE
启动服务失败，有什么办法知道失败的原因吗？

### ISSUE THREAD

**Issue by jianbaoshan** [wfrest/wfrest#238]
下面这种有概率性出现失败，有什么办法输出失败的原因吗
![image](https://github.com/user-attachments/assets/7c5892de-6a86-4558-b03b-0440bb66719c)

**Comment by Barenboim** [comment]
看一下errno就可以了。

**Comment by jianbaoshan** [comment]
好的 谢谢

**Comment by jianbaoshan** [comment]
这边遇到下面的错误打印，Wwfrest有什么方法使用SO_REUSEADDR这个配置吗
![image](https://github.com/user-attachments/assets/c969acc7-388d-457b-8d52-29c2b8cbc209)

**Comment by jianbaoshan** [comment]
好的 谢谢 我查查
