### ISSUE TITLE
https通信报curl: (56) Recv failure: Connection reset by peer

### ISSUE THREAD

**Issue by atzshjh** [wfrest/wfrest#239]
int main(int argc, char **argv)
{
    // in cert file 
    // sudo ./gen.sh to generate crt / key files
	if (argc != 3)
	{
		fprintf(stderr, "%s [cert file] [key file]\n",
				argv[0]);
		exit(1);
	}

    signal(SIGINT, sig_handler);

    HttpServer svr;

    // curl -v http://ip:port/https
    svr.GET("/https", [](const HttpReq *req, HttpResp *resp)
    {
        fprintf(stderr, "start server resp.\n");
        resp->String("Test Https\n");
    });

    if (svr.start("127.0.0.1", 8888, argv[1], argv[2]) == 0)
    {
        wait_group.wait();
        svr.stop();
    } else
    {
        fprintf(stderr, "Cannot start server\n");
        exit(1);
    }
    return 0;

运行命令：./19_https /data/code/http_project/wfrest/example/cert/server.crt /data/code/http_project/wfrest/example/cert/server.key
使用curl测试：curl -v -k http://127.0.0.1:8888/https --cert ./client.crt --key ./client.key
无法进行通信，请问有更具体的用例吗，谢谢。

**Comment by Barenboim** [comment]
curl不传crt和key可以吗。wfrest默认也不会进行验证。

**Comment by Barenboim** [comment]
或者浏览器打开试试。

**Comment by atzshjh** [comment]
![image](https://github.com/user-attachments/assets/7ae51380-5399-4b84-8f76-cd45cd55f4c3)
不传也不行，报的错是一样的

**Comment by atzshjh** [comment]
@Barenboim 或者有没有测试过的client的crt和key的生成方式，是不是文件的问题？

**Comment by Barenboim** [comment]
> @Barenboim 或者有没有测试过的client的crt和key的生成方式，是不是文件的问题？

和cliet的crt没有关系。server能启动成功，理论上就可以了。
你用workflow的tutorial-01_wget试试，直接：
$ ./wget https://127.0.0.1:8888/https
理论上不应该有问题。我这边也试一下。

**Comment by atzshjh** [comment]
> 或者浏览器打开试试。

浏览器刚测试了也不行

**Comment by atzshjh** [comment]
> ./wget https://127.0.0.1:8888/https

![image](https://github.com/user-attachments/assets/ecc44cec-e1d1-4338-913a-c58789210db0)
没问题，可以通信

**Comment by Barenboim** [comment]
那就是没有问题的了。我这边用浏览器实验了，也没有问题的。

你的curl命令，没有加"https"，你写的是"http"。

**Comment by atzshjh** [comment]
@Barenboim 不好意思，我的问题，地址应该是https，写错了，谢谢您

**Comment by Barenboim** [comment]
嗯嗯，没是。自签名证书curl默认可能验证不通过，可以设置一下。

**Comment by atzshjh** [comment]
@Barenboim 直接拷贝的你们代码里的注释，有机会可以改下，容易看漏

**Comment by Barenboim** [comment]
我改一下注释

**Comment by atzshjh** [comment]
已解决

**Comment by atzshjh** [comment]
@Barenboim 请问一个问题：为什么使用https不需要cert和key也能通信呢？那如果想基于wfrest来进行加密通信，该如何实现？
谢谢

**Comment by Barenboim** [comment]
只有是https就都是加密的，可以放心。

client加证书是为了server可以认证client，workflow的server默认不对cliient进行认证，如果需要对client认证，可以参考这个：https://github.com/sogou/workflow/issues/1121#issuecomment-1359359581 ，需要对server派生一下，实现一个虚函数。

workflow的client如果要进行双向认证，也需要设置ssl_ctx，可以通过WFGlobal::get_ssl_client_ctx()取出全局的ctx进行设置，也可以为http task设置独立的ssl ctx。

总之，如果你只是为了加密，这些都没有必要。

**Comment by atzshjh** [comment]
> 只有是https就都是加密的，可以放心。
> 
> client加证书是为了server可以认证client，workflow的server默认不对cliient进行认证，如果需要对client认证，可以参考这个：[sogou/workflow#1121 (comment)](https://github.com/sogou/workflow/issues/1121#issuecomment-1359359581) ，需要对server派生一下，实现一个虚函数。
> 
> workflow的client如果要进行双向认证，也需要设置ssl_ctx，可以通过WFGlobal::get_ssl_client_ctx()取出全局的ctx进行设置，也可以为http task设置独立的ssl ctx。
> 
> 总之，如果你只是为了加密，这些都没有必要。

收到，谢谢。
