### ISSUE TITLE
是否支持对客户端进行密码验证的功能？

### ISSUE THREAD

**Issue by atzshjh** [wfrest/wfrest#240]
@Barenboim 请教大佬，我想对客户端进行密码或者其他方式的验证，验证通过才可以进行通信，请问是否有这类接口，谢谢。

**Comment by chanchann** [comment]
这里在服务端写个Passwor校验类就行了吧，如果没有校验成功就不进行服务

**Comment by atzshjh** [comment]
说的有道理，那就自己加一个，谢谢。
