### ISSUE TITLE
/register/{deviceid}会覆盖/register

### ISSUE THREAD

**Issue by wangyongxiao** [wfrest/wfrest#243]
/register/{deviceid}会覆盖/register

我想实现/register返回所有条目的信息
/register/{id}返回指定id的条目信息
但是/register/{deviceid}会覆盖/register
调用/register会报找不到路径
这个有什么方式处理吗？

**Comment by Barenboim** [comment]
合理的方式，/register/{deviceid}应该完全不能匹配/register吧？

**Comment by Barenboim** [comment]
我这边试了一下，没有你说的这个问题啊？可以正常匹配"/register"这个handler。

你检查一下是不是拼写问题。
