### ISSUE TITLE
gcc 6.3编译问题

### ISSUE THREAD

**Issue by famoustang** [wfrest/wfrest#244]
/home/tym/workspace/wfrest/_include/wfrest/json.hpp:12376:91: internal compiler error: same canonical type node for different types nlohmann::detail::json_reverse_iterator<Base>::base_iterator and std::reverse_iterator<_Iterator>
     explicit json_reverse_iterator(const base_iterator& it) noexcept : base_iterator(it) {}
                                                                                           ^
0x835ba44 comptypes(tree_node*, tree_node*, int)
        /home/sying/SDK_CPU_UNIFIED/build/script/aarch64-himix100-linux/aarch64_himix100_build_dir/src/gcc-6.3.0/gcc/cp/typeck.c:1435
0x823ebee resolve_typename_type(tree_node*, bool)
        /home/sying/SDK_CPU_UNIFIED/build/script/aarch64-himix100-linux/aarch64_himix100_build_dir/src/gcc-6.3.0/gcc/cp/pt.c:23601
0x835986d structural_comptypes
        /home/sying/SDK_CPU_UNIFIED/build/script/aarch64-himix100-linux/aarch64_himix100_build_dir/src/gcc-6.3.0/gcc/cp/typeck.c:1199
0x835b9a8 comptypes(tree_node*, tree_node*, int)
        /home/sying/SDK_CPU_UNIFIED/build/script/aarch64-himix100-linux/aarch64_himix100_build_dir/src/gcc-6.3.0/gcc/cp/typeck.c:1445
0x8359757 structural_comptypes
        /home/sying/SDK_CPU_UNIFIED/build/script/aarch64-himix100-linux/aarch64_himix100_build_dir/src/gcc-6.3.0/gcc/cp/typeck.c:1357
0x835b9a8 comptypes(tree_node*, tree_node*, int)
        /home/sying/SDK_CPU_UNIFIED/build/script/aarch64-himix100-linux/aarch64_himix100_build_dir/src/gcc-6.3.0/gcc/cp/typeck.c:1445
0x835ca0b compparms(tree_node const*, tree_node const*)
        /home/sying/SDK_CPU_UNIFIED/build/script/aarch64-himix100-linux/aarch64_himix100_build_dir/src/gcc-6.3.0/gcc/cp/typeck.c:1537
0x82b8dc2 add_method(tree_node*, tree_node*, tree_node*)
        /home/sying/SDK_CPU_UNIFIED/build/script/aarch64-himix100-linux/aarch64_himix100_build_dir/src/gcc-6.3.0/gcc/cp/class.c:1157
0x83b7f51 finish_member_declaration(tree_node*)
        /home/sying/SDK_CPU_UNIFIED/build/script/aarch64-himix100-linux/aarch64_himix100_build_dir/src/gcc-6.3.0/gcc/cp/semantics.c:3007
0x83439d0 cp_parser_member_declaration
        /home/sying/SDK_CPU_UNIFIED/build/script/aarch64-himix100-linux/aarch64_himix100_build_dir/src/gcc-6.3.0/gcc/cp/parser.c:22625
0x8344f94 cp_parser_member_specification_opt
        /home/sying/SDK_CPU_UNIFIED/build/script/aarch64-himix100-linux/aarch64_himix100_build_dir/src/gcc-6.3.0/gcc/cp/parser.c:22186
0x8344f94 cp_parser_class_specifier_1
        /home/sying/SDK_CPU_UNIFIED/build/script/aarch64-himix100-linux/aarch64_himix100_build_dir/src/gcc-6.3.0/gcc/cp/parser.c:21378
0x832214a cp_parser_class_specifier
        /home/sying/SDK_CPU_UNIFIED/build/script/aarch64-himix100-linux/aarch64_himix100_build_dir/src/gcc-6.3.0/gcc/cp/parser.c:21614
0x832214a cp_parser_type_specifier
        /home/sying/SDK_CPU_UNIFIED/build/script/aarch64-himix100-linux/aarch64_himix100_build_dir/src/gcc-6.3.0/gcc/cp/parser.c:15868
0x8322411 cp_parser_decl_specifier_seq
        /home/sying/SDK_CPU_UNIFIED/build/script/aarch64-himix100-linux/aarch64_himix100_build_dir/src/gcc-6.3.0/gcc/cp/parser.c:12788
0x8341aad cp_parser_single_declaration
        /home/sying/SDK_CPU_UNIFIED/build/script/aarch64-himix100-linux/aarch64_himix100_build_dir/src/gcc-6.3.0/gcc/cp/parser.c:25803
0x8341e48 cp_parser_template_declaration_after_parameters
        /home/sying/SDK_CPU_UNIFIED/build/script/aarch64-himix100-linux/aarch64_himix100_build_dir/src/gcc-6.3.0/gcc/cp/parser.c:25498
0x83426d6 cp_parser_explicit_template_declaration
        /home/sying/SDK_CPU_UNIFIED/build/script/aarch64-himix100-linux/aarch64_himix100_build_dir/src/gcc-6.3.0/gcc/cp/parser.c:25730
0x83429f8 cp_parser_template_declaration_after_export
        /home/sying/SDK_CPU_UNIFIED/build/script/aarch64-himix100-linux/aarch64_himix100_build_dir/src/gcc-6.3.0/gcc/cp/parser.c:25748
0x8346caf cp_parser_declaration
        /home/sying/SDK_CPU_UNIFIED/build/script/aarch64-himix100-linux/aarch64_himix100_build_dir/src/gcc-6.3.0/gcc/cp/parser.c:12123
Please submit a full bug report,
with preprocessed source if appropriate.
Please include the complete backtrace with any bug report.
See <http://gcc.gnu.org/bugs.html> for instructions.

这是个已知问题，是由于nlohmann模块代码引起的问题，在https://github.com/nlohmann/json/issues/1906 和 https://github.com/eProsima/Fast-DDS/issues/1608 有讨论，
这个编译器是海思的hi3559av100的编译器，移植的时候遇到的问题，目前来看升级编译器的可能 性较低，是否可以修改代码来解决？

**Comment by Barenboim** [comment]
是否可以通过升级nlohmann JSON来解决呢？

**Comment by famoustang** [comment]
> 是否可以通过升级nlohmann JSON来解决呢？

我查了一下nlohmann 仓库的更新，根据讨论的情况来看，他们并没有对代码进行修改的打算，所以如果要快速解决可能这边修改比较合适

**Comment by Barenboim** [comment]
你这边看起来也无需用到nlohmann JSON吧？我有考虑过主分支把nlohmann删除，只保留wfrest::Json。至少我们可先建一个不包含nlohmann JSON的分支。

**Comment by famoustang** [comment]
> 你这边看起来也无需用到nlohmann JSON吧？我有考虑过主分支把nlohmann删除，只保留wfrest::Json。至少我们可先建一个不包含nlohmann JSON的分支。

不用nlohmann ，剥离是个好办法，会不会工作量太大？

**Comment by Barenboim** [comment]
工作量还好，查找一下都给去了。

不太敢直接改在main分支，我们用户里还是有不少会使用nlohmann JSON的。虽然wfrest::Json性能上其实好很多。

**Comment by famoustang** [comment]
> 工作量还好，查找一下都给去了。
> 
> 不太敢直接改在main分支，我们用户里还是有不少会使用nlohmann JSON的。虽然wfrest::Json性能上其实好很多。

或者是说做个兼容，增加个配置选项，选择性编译。

**Comment by Barenboim** [comment]
> > 工作量还好，查找一下都给去了。
> > 不太敢直接改在main分支，我们用户里还是有不少会使用nlohmann JSON的。虽然wfrest::Json性能上其实好很多。
> 
> 或者是说做个兼容，增加个配置选项，选择性编译。

我们这边的特点是，不会有编译期的功能选项。我一会直接删除搞个branch吧。另外，你也可以考虑直接用[workflow](https://github.com/sogou/workflow)。

**Comment by famoustang** [comment]
> 用这个分支吧：https://github.com/wfrest/wfrest/tree/json
> 
> 也麻烦star一下项目。

好的，star项目了
