### ISSUE TITLE
漏洞扫描扫出来的问题，这个解决了吗

### ISSUE THREAD

**Issue by jianbaoshan** [wfrest/wfrest#249]

**Comment by jianbaoshan** [comment]
<img width="308" alt="a62f1137f67396a39d0ad0c5ca4f78f" src="https://github.com/user-attachments/assets/1719b107-695b-42bd-8491-bb1404cfafbf">

**Comment by Barenboim** [comment]
之前没有人报告过。你那边发现的么？我确认一下。

**Comment by jianbaoshan** [comment]
是的  扫出漏洞了

**Comment by Barenboim** [comment]
这个问题应该只出现在加载静态资源吧？使用``Static()``那个接口才会？

**Comment by Barenboim** [comment]
@jianbaoshan 麻烦发一下你是怎么注册handler，以及怎么处理才引起这个问题的。

**Comment by Barenboim** [comment]
这个应该是你业务层代码的问题，我们的example里，有对这个问题进行说明：
https://github.com/wfrest/wfrest/blob/19cd7c1bd4947251248c59a2f2ea90bbd2769f36/example/08_upload_file.cc#L38

不可以直接信任通过form格式或URL发送过来的文件路径信息，需要业务逻辑里对路径进行处理。

**Comment by jianbaoshan** [comment]
这是静态文件注册的接口
![image](https://github.com/user-attachments/assets/2353346c-c952-43fb-9d9d-1eb7acf82189)

**Comment by jianbaoshan** [comment]
这是静态文件注册的接口
![image](https://github.com/user-attachments/assets/2353346c-c952-43fb-9d9d-1eb7acf82189)

**Comment by jianbaoshan** [comment]
我这样注册静态文件，如何规避这个漏洞？

**Comment by Barenboim** [comment]
还真是有这个问题。这里需要修复一下！

**Comment by jianbaoshan** [comment]
你好 这边大概什么时候可以解决  我们这边有点急

**Comment by Barenboim** [comment]
我今天搞一下吧。只影响Static整个目录的情况。





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月24日(周四) 上午9:06
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wfrest/wfrest] 漏洞扫描扫出来的问题，这个解决了吗 (Issue #249)




 
你好 这边大概什么时候可以解决  我们这边有点急

**Comment by Barenboim** [comment]
https://github.com/wfrest/wfrest/pull/251

**Comment by Barenboim** [comment]
麻烦试一下这个！

**Comment by jianbaoshan** [comment]
非常感谢 我们更新试试

**Comment by jianbaoshan** [comment]
我更新了  好像还是存在

**Comment by jianbaoshan** [comment]
我们使用的是绿盟

**Comment by Barenboim** [comment]
> 我更新了 好像还是存在

不会吧？你看一下修改的具体内容，在一开始就对路径进行了处理啊，不应该还有这个问题。而且我也测试过的，可以解决。

你能否给我一个最小可复现的例子，以及访问时的URL形式。

**Comment by Barenboim** [comment]
我想了想，好像只处理了路由时的路径，如果路径匹配成功，好像还是有问题。。。我尽快再改一版。

**Comment by Barenboim** [comment]
你尽量还是给我一个最小可复现的例子。

**Comment by jianbaoshan** [comment]
指的是静态文件吗

**Comment by Barenboim** [comment]
给一段可以复现漏洞的最小代码。







---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月27日(周日) 下午3:24
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wfrest/wfrest] 漏洞扫描扫出来的问题，这个解决了吗 (Issue #249)




 
指的是静态文件吗

**Comment by jianbaoshan** [comment]
主要就是这个  其他代码与这个漏洞没有关系
![image](https://github.com/user-attachments/assets/c74c1975-de33-4b27-b987-594e8cffee46)

**Comment by jianbaoshan** [comment]
这个是文件目录
![image](https://github.com/user-attachments/assets/713acb5b-71f9-41f5-9244-5478437903e7)

**Comment by Barenboim** [comment]
不是。。。


你要给我一段我可以直接用来复现bug的代码。不要给我图，也不是你现在代码的一部分。




是：最小可复现问题的完整代码。







---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月27日(周日) 下午3:50
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wfrest/wfrest] 漏洞扫描扫出来的问题，这个解决了吗 (Issue #249)




 
主要就是这个  其他代码与这个漏洞没有关系
 image.png (view on web)

**Comment by jianbaoshan** [comment]
这个确实解决了，现在拿不到其他目录的文件了  非常感谢
