### ISSUE TITLE
使用awvs软件扫描漏洞的时候 在最开始就挂掉了

### ISSUE THREAD

**Issue by jianbaoshan** [wfrest/wfrest#252]
![image](https://github.com/user-attachments/assets/6d7d3799-d042-43f5-9c80-93a25d8b974a)

**Comment by Barenboim** [comment]
还是那句话，你能不能给我一段可以复现问题的代码，不是给我一个什么信息都没有的图片……

**Comment by jianbaoshan** [comment]
有没有邮箱  我把代码发给你

**Comment by Barenboim** [comment]
不是要你的代码，是让你写一段最小可复现的代码！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月28日(周一) 中午1:39
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wfrest/wfrest] 使用awvs软件扫描漏洞的时候 在最开始就挂掉了 (Issue #252)




 
有没有邮箱  我把代码发给你

**Comment by Barenboim** [comment]
为什么需要gz? 我是说最小代码，方便我编译的。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月28日(周一) 中午1:51
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wfrest/wfrest] 使用awvs软件扫描漏洞的时候 在最开始就挂掉了 (Issue #252)




 
Uploading test.tar.gz…

**Comment by jianbaoshan** [comment]
解压之后 可以直接make编译

**Comment by Barenboim** [comment]
我还没打开。但这个bug我觉得要复现也是十行代码的事啊。真的需要发一个工程？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月28日(周一) 中午1:54
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wfrest/wfrest] 使用awvs软件扫描漏洞的时候 在最开始就挂掉了 (Issue #252)




 
解压之后 可以直接make编译

**Comment by jianbaoshan** [comment]
[Uploading main.c…]()

**Comment by jianbaoshan** [comment]
这个文件看看

**Comment by Barenboim** [comment]
你就贴issue里吧😂 我打不开啊。

你把十几行代码贴在issue里有什么问题吗？

**Comment by Barenboim** [comment]
不要贴你的业务代码，贴一个可复现代码！你起码要大概知道出问题的逻辑吧？然后写一个相同逻辑的代码就可以了。不要贴原始代码！

**Comment by jianbaoshan** [comment]
int weblct_register_http_server_for_static_file(void *svr)
{
	char path_name[128], dist_path[64];
	HttpServer *server = (HttpServer *)svr;
	
	printf("register static file\n");

	memset(dist_path, 0, 64);
	sprintf(dist_path, "/app/backup/WebLCT/config/client/%s/dist", weblct_common.client.name);

	// register static file
	memset(path_name, 0, 128);
	sprintf(path_name, "%s/static", dist_path);
	server->Static("/static", path_name);

	memset(path_name, 0, 128);
	sprintf(path_name, "%s", dist_path);
	server->Static("/public", path_name);

	memset(path_name, 0, 128);
	sprintf(path_name, "%s/index.html", dist_path);
	server->Static("/", path_name);
	server->set_default_route("/");

	return 0;
}

**Comment by jianbaoshan** [comment]
主要就是这个  注册了静态文件的接口导致的

**Comment by Barenboim** [comment]
好的。然后，使用一个什么样的URL，可以访问到其他目录的文件呢？给一个可以产生问题的request URL。

**Comment by Barenboim** [comment]
其实，你这个程序，依然不符合最小化原则。你注册了3个Static。

如果是为了方便我们排查，最好是把代码继续简化。现在我不得不自己在进一步裁剪。

**Comment by Barenboim** [comment]
你先给出一个可以产生问题的URL，让我可以知道是哪个Static出的问题。

**Comment by Barenboim** [comment]
我感觉你真的是完全忽略了我说的不要贴原始代码这句话……

你下次报问题，最好先了解一下对开源项目报bug的方式。否则现在效率真的很低。

**Comment by Barenboim** [comment]
https://stackoverflow.com/help/minimal-reproducible-example

可以先看一下这个文档，下次提问我们可以提升效率。

**Comment by jianbaoshan** [comment]
使用漏洞扫描软件 我也不知道具体是哪个URL

**Comment by jianbaoshan** [comment]
#249 这个问题也是这个static导致的

**Comment by jianbaoshan** [comment]
主要是这个接口导致的漏洞
![image](https://github.com/user-attachments/assets/388b873b-073c-4daf-a908-c843f88e4f5e)

**Comment by Barenboim** [comment]
那我不是更不知道😭


我根据你提供的信息，根本就无发复现问题现在！



你报上一个issue时，确实是有漏洞的。改了之后，我已经完全复现不出问题。


其实你上一个issue就是因为什么信息也没提供，我硬是一点点猜的。你现在又让我硬猜？





---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月28日(周一) 下午5:05
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wfrest/wfrest] 使用awvs软件扫描漏洞的时候 在最开始就挂掉了 (Issue #252)




 
使用漏洞扫描软件 我也不知道具体是哪个URL

**Comment by jianbaoshan** [comment]
awvs软件我安装了一个 可以抓包看到URL   #249 这个使用的绿盟软件  我这边没有环境 无法提供抓包

**Comment by jianbaoshan** [comment]
这是 252抓包的截图
![image](https://github.com/user-attachments/assets/796fceca-7901-44f9-bbaa-d86ac16058df)

**Comment by jianbaoshan** [comment]
#249 如果需要抓包数据  我可以去要一下   比较麻烦

**Comment by Barenboim** [comment]
我真的是。。。。




报问题不是这么报的，不是随便截图让我分析。你要把有效信息给我！


说白了，给我最小可复现程序和URL！！！



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月28日(周一) 下午5:17
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wfrest/wfrest] 使用awvs软件扫描漏洞的时候 在最开始就挂掉了 (Issue #252)




 
这是 252抓包的截图
 image.png (view on web)

**Comment by jianbaoshan** [comment]
这里无法把抓包文件上传

**Comment by Barenboim** [comment]
你能不能看一我给你发的文档链接。你这是要逼疯开发者的节奏。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月28日(周一) 下午5:17
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wfrest/wfrest] 使用awvs软件扫描漏洞的时候 在最开始就挂掉了 (Issue #252)




 
#249 如果需要抓包数据  我可以去要一下   比较麻烦

**Comment by Barenboim** [comment]
不要再上传文件了！！！
给我最小的有效信息就可以了，懂吗？



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年10月28日(周一) 下午5:20
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wfrest/wfrest] 使用awvs软件扫描漏洞的时候 在最开始就挂掉了 (Issue #252)




 
这里无法把抓包文件上传

**Comment by Barenboim** [comment]
> 主要是这个接口导致的漏洞 ![image](https://private-user-images.githubusercontent.com/38252454/380646230-388b873b-073c-4daf-a908-c843f88e4f5e.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzAxMDc3ODUsIm5iZiI6MTczMDEwNzQ4NSwicGF0aCI6Ii8zODI1MjQ1NC8zODA2NDYyMzAtMzg4Yjg3M2ItMDczYy00ZGFmLWE5MDgtYzg0M2Y4OGU0ZjVlLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEwMjglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMDI4VDA5MjQ0NVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZhNGVhNTI1M2IzZjJmMTk5OTZjYzEwOTM4MjU0Y2JjZWEyN2MzNDUzNTJhZmNkODc4ZTAxZjYwYWFiZjJmODEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.ixBTeQxnbGKXDcmrkE8po9v56b1CuEOTGiUQHJ6ohUk)

1、不要发图！

2、这个不叫最小可复现程序，我没有办法通过编译的方式来查问题。

**Comment by Barenboim** [comment]
https://github.com/ryanhanwu/How-To-Ask-Questions-The-Smart-Way

你看完这个之前不要再提问了。

**Comment by Barenboim** [comment]
如果没有更多的信息可以提供，这个issue我先关了。

**Comment by Barenboim** [comment]
最新的release应该解决了这个问题。
