### ISSUE TITLE
Problem with the SSL certificate

### ISSUE THREAD

**Issue by haomingbai** [wfrest/wfrest#255]
I cannot load the all certs on the chain like what other net libs.
Code:
```
#include <wfrest/HttpServer.h>
#include <utility>

int main()
{
    using namespace wfrest;

    std::unique_ptr<HttpServer> server = std::make_unique<HttpServer>();

    server->POST("/hi", [](const HttpReq *req, HttpResp *res) { res->Json(req->json()); });

    int flag = server->start("0.0.0.0", 2345, "/nwpu.space_bundle.crt", "/nwpu.space.key");

    if (flag)
    {
        std::cerr << "Server start fail!" << std::endl;
    }
    else
    {
        std::clog << "Server start success!" << std::endl;
        while (getchar() != 'q')
            ;
        server->stop();
    }
}
```
However, when checking the certificates on \
https://www.myssl.cn/tools/check-server-cert.html \
it is shown that the certificate chain is not complete
![image](https://github.com/user-attachments/assets/3280b62e-d8e0-40b4-a68d-6ce061a032c7)

However, when I write a set of restful api with cpp-httplib or other tools, I can see the complete cert chain like this:
![image](https://github.com/user-attachments/assets/7cc17393-7086-4b28-ace6-fe652754009d)
Code:
```
#define CPPHTTPLIB_OPENSSL_SUPPORT

#include <httplib.h>

int main()
{
        httplib::SSLServer svr("/nwpu.space_bundle.crt", "/nwpu.space.key");
        svr.Post("/hi", [](const httplib::Request &, httplib::Response &res) {
        res.set_content("Hello World!", "text/plain");
});
svr.listen("0.0.0.0",2345);
}
```
What's happened? it is important because it sometimes matters to some clients

**Comment by Barenboim** [comment]
Sorry, we don't set any SSL certification default. You need to derive from ``wfrest::HttpServer`` to set SSL certification on SSL_CTX  by yourself.   You may refer to this issue: https://github.com/sogou/workflow/issues/1121#issuecomment-1359359581

BTW, I still don't know what exact SSL functions you need to call. It would be appreciated if you tell us how to solve this problem.

**Comment by Barenboim** [comment]
如上，通过派生server重写new_ssl_ctx函数可以实现认证链。具体怎么调用SSL认证函数我不太懂。如果解决了问题，欢迎把具体代码贴一下。

**Comment by Barenboim** [comment]
It's like you are using httplib::SSLServer this constructor: 
https://github.com/yhirose/cpp-httplib/blob/924f214303b860b78350e1e2dfb0521a8724464f/httplib.h#L9083

**Comment by Barenboim** [comment]
~~~
SSL_CTX_use_certificate_chain_file() should be used instead of the
       SSL_CTX_use_certificate_file() function in order to allow the use of
       complete certificate chains even when no trusted CA storage is used or
       when the CA issuing the certificate shall not be added to the trusted
       CA storage.
~~~

Maybe I need to update code to use SSL_CTX_use_certificate_chain_file instead.

**Comment by Barenboim** [comment]
PR: https://github.com/sogou/workflow/pull/1641

**Comment by Barenboim** [comment]
麻烦把workflow升级到最新版本再试一下，如果可以解决了请反馈一下。

**Comment by haomingbai** [comment]
可以用了，太感谢了

**Comment by haomingbai** [comment]
可以永乐
