### ISSUE TITLE
有什么方法可以注册个回调函数，只要有任何客户端的请求都先进入这个回调函数中吗

### ISSUE THREAD

**Issue by jianbaoshan** [wfrest/wfrest#257]
@chanchann 大佬 现在想在每一个客户端请求进来之前先校验之后再执行，有什么方法可以做到吗   谢谢

**Comment by Barenboim** [comment]
https://github.com/wfrest/wfrest/blob/main/docs/cn/aop.md

**Comment by jianbaoshan** [comment]
@Barenboim 大佬  这个aop中before如果返回错误，可以不执行服务吗？我这边的需求是检查token成功就执行服务，检查token失败就直接返回错误，不执行服务了

**Comment by Barenboim** [comment]
> @Barenboim 大佬 这个aop中before如果返回错误，可以不执行服务吗？我这边的需求是检查token成功就执行服务，检查token失败就直接返回错误，不执行服务了

是的。试一下吧。这个返回值的意义还是挺明显的。

**Comment by jianbaoshan** [comment]
我试了  检查token失败 直接返回falsh，还是会执行服务的
![image](https://github.com/user-attachments/assets/2ea8fa53-7ea6-4a0c-8b73-6a327891478c)
![image](https://github.com/user-attachments/assets/330afe79-997a-4d44-bbd1-b46c496666af)

**Comment by Barenboim** [comment]
是噢，居然没有处理返回值：
https://github.com/wfrest/wfrest/blob/cd6d2652c3ed52499d484b2150bce492abb489b9/src/core/BluePrint.cc#L16
我看看怎么改合理一点。

**Comment by Barenboim** [comment]
再说一下，贴程序的话最好贴完整一点，我看不到你是怎么注册进去的。

虽然里面有一些处理不太合理，但好像只有global aspect是不处理返回值的，并不是所有都不处理。你把怎么注册的代码也贴一下。

@jianbaoshan

**Comment by Barenboim** [comment]
从我这边看，对单个方法的AOP是正常的，只要before返回false并不执行handler。global aop的话，就都会执行。

不过handler的AOP也有一些小问题，当注册多个切面的时候，只要有一个before不成功，所有的after也都不执行了，这个不太好。对于部分成功的before，after应该也执行。

不过你不注册多个切面也不存在这个问题。

**Comment by jianbaoshan** [comment]
我这边就使用svr.Use(FirstAop());来注册一个全局的aop
![image](https://github.com/user-attachments/assets/b49edc2a-87d0-459b-8e65-2e8c2bd61fb0)
![image](https://github.com/user-attachments/assets/0aa48ddc-4407-4cb4-bfef-384c38a66438)

**Comment by Barenboim** [comment]
感觉现在的实现有点不合理，你先用单个handler的吧，我整体改一下。



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2024年11月14日(周四) 上午9:14
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [wfrest/wfrest] 有什么方法可以注册个回调函数，只要有任何客户端的请求都先进入这个回调函数中吗 (Issue #257)




 
我这边就使用svr.Use(FirstAop());来注册一个全局的aop
 image.png (view on web)
 image.png (view on web)

**Comment by jianbaoshan** [comment]
好的  我先使用单个的handler试试

**Comment by chanchann** [comment]
@jianbaoshan 可以试试新的main分支，有几个地方before忘记处理返回值了

**Comment by jianbaoshan** [comment]
好的  我试试

**Comment by jianbaoshan** [comment]
非常感谢，测试了没有问题
