### ISSUE TITLE
Help me ! I encountered Segmentation fault

### ISSUE THREAD

**Issue by yangyangyyyyy** [wfrest/wfrest#258]
I started the server using quick start code. When i use browser to connect , it said empty message and server exit. so i debug it and found segmentation fault in http_parser.
我是用的快速开始的里面的代码 我用浏览器测试的是一连服务器就直接崩了，程序自动退出了 我调试了一下发现段错误。。
![1](https://github.com/user-attachments/assets/26ac67ce-9042-4219-9ef2-c8db39ac46f4)
![2](https://github.com/user-attachments/assets/06a89cd1-c4e6-42d6-bd79-75acb6220f9b)
![微信截图_20241114145816](https://github.com/user-attachments/assets/12266740-d9b6-4656-9556-28cf16bb63a4)

**Comment by Barenboim** [comment]
你好。你是使用wfrest还是workflow？运行的是哪一个示例呢。

应该是环境的问题。是否之前安装过workflow库，导致头文件不一致之类的问题。

**Comment by yangyangyyyyy** [comment]
> 你好。你是使用wfrest还是workflow？运行的是哪一个示例呢。
> 
> 应该是环境的问题。是否之前安装过workflow库，导致头文件不一致之类的问题。

谢谢你的解答，我目前确实已经通过apt-get安装过workflow，删除掉就可以了吗，谢谢。
Thank you for your assistance. For now, I do have installed workflow through apt-get. if i remove/uninstall  it ,will this  resolve the problem? thank you.

**Comment by Barenboim** [comment]
是的，应该是版本冲突了，头文件不致导致的。



---Original---
From: ***@***.***&gt;
Date: Thu, Nov 14, 2024 17:00 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [wfrest/wfrest] Help me ! I encountered Segmentation fault (Issue#258)




  
你好。你是使用wfrest还是workflow？运行的是哪一个示例呢。
 
应该是环境的问题。是否之前安装过workflow库，导致头文件不一致之类的问题。
  
谢谢你的解答，我目前确实已经通过apt-get安装过workflow，删除掉就可以了吗，谢谢。
 Thank you for your assistance. For now, I do have installed workflow through apt-get. if i remove/uninstall  it ,will this  resolve the problem? thank you.

**Comment by yangyangyyyyy** [comment]
> 是的，应该是版本冲突了，头文件不致导致的。
> […](#)
> ---Original--- From: ***@***.***&gt; Date: Thu, Nov 14, 2024 17:00 PM To: ***@***.***&gt;; Cc: ***@***.******@***.***&gt;; Subject: Re: [wfrest/wfrest] Help me ! I encountered Segmentation fault (Issue#258) 你好。你是使用wfrest还是workflow？运行的是哪一个示例呢。 应该是环境的问题。是否之前安装过workflow库，导致头文件不一致之类的问题。 谢谢你的解答，我目前确实已经通过apt-get安装过workflow，删除掉就可以了吗，谢谢。 Thank you for your assistance. For now, I do have installed workflow through apt-get. if i remove/uninstall it ,will this resolve the problem? thank you. — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you commented.Message ID: ***@***.***&gt;

谢谢你，刚刚我把用apt安装的删除掉了，运行发现缺少Workflow的各种头文件，于是我又去GitHub上拉取了最新的workflow进行make install安装，运行，报错/usr/local/include/wfrest/Json.h:4:10: fatal error: workflow/json_parser.h: No such file or directory
    4 | #include "workflow/json_parser.h"
      |          ^~~~~~~~~~~~~~~~~~~~~~~~缺少这个头文件。。。。。

**Comment by yangyangyyyyy** [comment]
> 没有道理啊，这个文件在`/usr/local/workflow/include`里，你手动找一些。
> 
> 你也可以直接：
> 
> ```shell
> $ git clone https://github.com/wfrest/wfrest --recursive
> ```
> 
> 然后直接在wfrest根目录下进行make。其实大多数情况下，跑一跑demo也没有必要安装。

谢谢你，不过我已经放弃了，workflow我又重装了一下，json_parser头文件缺少解决了，但我一启动又段错误了。。。太折磨了

**Comment by Barenboim** [comment]
要不你直接用workflow试试？比较简单一点，不用依赖。

这两个项目都不会有什么明显的问题的。
