### ISSUE TITLE
执行make check报错，但是我gcc是最新版本

### ISSUE THREAD

**Issue by zsy996** [wfrest/wfrest#266]
<img width="1267" alt="Snipaste_2024-12-22_14-29-38" src="https://github.com/user-attachments/assets/7b2e6d5e-a6c8-4916-9566-13a3d124ce94" />
怎么解决呢

**Comment by Barenboim** [comment]
应该是新版gtest要求c++14的原因。项目的ci里有运行test的，可放心使用。

或者你在test目录里把标准改成c++14试一下。

**Comment by Barenboim** [comment]
好了，我把test改成用C++14编译了，可以再试一下。
