### ISSUE TITLE
有没有计划支持Windows版本？

### ISSUE THREAD

**Issue by xuebing1995** [wfrest/wfrest#66]
有计划支持Windows版本的workflow吗？

**Comment by chanchann** [comment]
目前暂时完善linux版本，暂时还没有支持windows版本的计划

**Comment by xuebing1995** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by Barenboim** [comment]
主要是workflow的Windows本身少了文件任务。wfrest我看了一下好像平台无关的。

**Comment by xuebing1995** [comment]
> 主要是workflow的Windows本身少了文件任务。wfrest我看了一下好像平台无关的。

嗯，我改了改在Windows可以正常跑了，但是文件IO部分看workflow说会支持Windows的异步IO，这个有时间点吗？

**Comment by Barenboim** [comment]
如果你如果在windows下跑，不使用wfrest::HttpResp::File()接口，直接IO完用String一般还更快。因为这个File每次都走异步，对小文件反而慢。
workflow的Windows版，现在没有全职开发可以投入……

**Comment by xuebing1995** [comment]
> 如果你如果在窗户下跑，不使用wfrest :: HttpResp ::文件（）接口，直接IO完用字符串一般还更快。因为这个文件每次都走异步，对小文件反而慢。 工作流程的视窗版，现在没有全职开发可以……

ok,thank you for your reply.

**Comment by xuebing1995** [comment]
> 老哥，改好的windows库能发一下吗？我也想在windows上面试一下

邮箱发下 给你发过去

**Comment by kkzi** [comment]
@xuebing1995   kizi#qq.com 铜球

**Comment by xuebing1995** [comment]
> @xuebing1995 kizi#qq.com 铜球

上传到github上了，有需要的自取吧。

**Comment by kkzi** [comment]
> > @xuebing1995 *#qq.com 铜球
> 
> 上传到github上了，有需要的自取吧。

已取，多谢
