### ISSUE TITLE
You'd better to add some shell script to create a new project by project name.

### ISSUE THREAD

**Issue by rareli** [wfrest/wfrest#70]

**Comment by rareli** [comment]
And the same time,you can show a full project to use database/json/configure file/daemon/services/upload and so on.
eg. mini blog.

**Comment by rareli** [comment]
html template: 
https://github.com/jinja2cpp/Jinja2Cpp

**Comment by chanchann** [comment]
Ok, thanks for your suggestion!

**Comment by rareli** [comment]
You can write a full example that use db(thread pool),nosql(redis/mongodb),image library and so on.similar the example project in cppcms(https://sourceforge.net/projects/cppcms/files/cppblog/).
This is important of full example for most of beginners.
And the same time,this is more conducive to this project promotion and application.

**Comment by chanchann** [comment]
Working on designing MySQL interface

**Comment by rareli** [comment]
> Working on designing MySQL interface

How to use MySQL thread pool in the page?
