### ISSUE TITLE
You'd better add the image library to show the captcha.

### ISSUE THREAD

**Issue by rareli** [wfrest/wfrest#75]
You'd better add the image library to show the captcha.

**Comment by chanchann** [comment]
I think it is not the responsibility of wfrest, users can choose the image lib they like which shows the captcha.

LIke gin(https://github.com/gin-gonic/gin), if you want to use captcha, you can import other lib like captcha

**Comment by rareli** [comment]
I say,you can give a full example that use db(thread pool),nosql(redis/mongodb),image library and so on.similar the example project in cppcms(https://sourceforge.net/projects/cppcms/files/cppblog/).
This is important of full example for most of beginners.
And the same time,this is more conducive to this project promotion and application.
