### ISSUE TITLE
Bug of code in readme

### ISSUE THREAD

**Issue by chunyang-wen** [wfrest/wfrest#80]
Please make sure that you have tested the code before put them into the README doc.

+ Such as no defined varable for `abc`
+ Missing semicolon

BTW, in order to build the example you provided, there maybe need some compiler flags to be set such `LD_LIBRARY_PATH`, or linking specify library, such as `-lworkflow`.

**Comment by chanchann** [comment]
Thanks for your suggestion! 

You can compile examples to run first.

Just run the shell script `./build.sh`

**Comment by chanchann** [comment]
The code in the example folder has been verified by CI and can be used directly.

**Comment by chanchann** [comment]
Have checked all the docs, 🍺
