### ISSUE TITLE
关于安装wfrest

### ISSUE THREAD

**Issue by lixiaoqian521** [wfrest/wfrest#94]
chan佬考虑从码云构建项目吗，在这边的话，会拦住一大部分初学者，访问不了github

**Comment by lixiaoqian521** [comment]
我觉得开源不放quickstart快一点，让更多用户使用起来，如果构建你的项目还需要我搭个梯子去访问github我觉得有点舍近逐远了，另外为了更友好，建议可以提示用户安装openssl和zlib

**Comment by lixiaoqian521** [comment]
提供一下安装命令

**Comment by chanchann** [comment]
https://gitee.com/wfrest/wfrest
